// ⚠ 자동 생성 파일 — 손으로 고치지 말 것. 대본 md 를 고친 뒤 `node scripts/build-story-script.mjs 19` 로 다시 만든다.
// EP05~EP19 오프닝(brief)/결말(outro) 대사 + 컷신 슬롯. 원본: 게임 개발 파일/울토르_메인스토리_대사_컷신_*.md (v1.1)
import type { StoryLine } from '@/lib/story'
import type { CutsceneDef } from '@/lib/cutscenes'

export const EP_SCRIPT_GEN: Record<number, { brief: StoryLine[]; outro: StoryLine[] }> = {
  // ═════════ EP05 · 깊은 숲으로 ═════════
  5: {
    brief: [
      {"speaker":"","text":"[방학 첫날] 에르디아 숲 입구. 학교 조사단 캠프가 세워진다. 매미 소리가 시끄럽다.","cut":null},
      {"speaker":"","text":"학생들이 짐을 내리고 텐트를 친다. 리안의 텐트만 세 번째로 무너진다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"방학인데 과제하러 산속까지 온 거 실화냐?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"네가 '학교 밖에서 배우는 게 더 재밌다'고 했잖아."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그건 풍경 좋은 데서 책 읽는다는 뜻이었지. 텐트랑 싸운다는 뜻이 아니라."},
      {"speaker":"도란","portraitId":"comp-doran","text":"말뚝을 반대로 박았어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……말뚝에도 앞뒤가 있어?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"있어."},
      {"speaker":"","text":"오웬이 조사 수첩을 펼친다. 방학인데도 셔츠 단추를 끝까지 잠갔다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이번 조사의 공식 목적은 세 가지입니다. 변이 몬스터의 흔적 확인, 고대 식생 기록 비교, 그리고 지난 학기 발견한 문양의 출처 조사."},
      {"speaker":"주인공","player":true,"text":"교수님은 안 오세요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"미르엘 교수님은 방학 중 교내 결계 정기 점검을 맡고 계십니다. 대신 이걸 주셨습니다."},
      {"speaker":"","text":"오웬이 작은 통신 수정구를 꺼낸다. 수정구 안에 쪽지 하나가 돌돌 말려 있다."},
      {"speaker":"","text":"「무리하지 말 것. 밥은 꼭 챙겨 먹을 것. 리안, 텐트 말뚝은 뾰족한 쪽이 아래란다.」"},
      {"speaker":"리안","portraitId":"comp-rian","text":"……교수님이 어떻게 아셔?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"작년 조사단도 똑같았나 보지."},
      {"speaker":"","text":"짧은 웃음. 그 웃음 위로, 숲 안쪽에서 낮은 울음소리가 들린다. 웃음이 멎는다."},
    ],
    outro: [
      {"speaker":"","text":"[이상한 숲] 셀린이 무릎을 꿇고 잎의 방향을 살핀다.","cut":null},
      {"speaker":"셀린","portraitId":"npc-potion","text":"전부 북쪽을 향해 누워 있어. 지난번 현장수업 때랑 같아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"바람은 남서풍이야. 바람 때문이 아니야."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"그리고… 이 잎, 한여름인데 새순처럼 연해. 숲 전체가 봄을 한 번 더 맞은 것 같아."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그거 좋은 거 아니에요? 숲이 건강하다는 거잖아요."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"사람도 열이 너무 나면 얼굴이 빨개지지. 건강해 보여도, 그건 아픈 거야."},
      {"speaker":"","text":"도란이 흙을 한 줌 들어 보인다. 아래층 흙이 위로 뒤집혀 있다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"밑에서 뭔가 밀고 올라온 흔적이야. 두더지 크기가 아니고."},
      {"speaker":"","text":"주인공이 뿌리 틈에서 작은 검은 결정을 발견한다. 손바닥에 올리자 미지근하다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이거… 지난 학기에 본 거잖아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"온도도 같아. 그때 교수님이 회수하신 거랑 같은 종류야.","anim":"sella-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이번엔 우리가 정식 조사단입니다. 표본으로 보관하고, 학교에 같이 보고하죠."},
      {"speaker":"","text":"야영지의 불이 꺼진 뒤, 카메라가 숲 위로 떠오른다.","cut":"ep05-a"},
      {"speaker":"","text":"뿌리 사이로 금빛 섞인 검은빛이 하나씩 점멸한다. 반딧불이처럼, 그러나 반딧불이보다 느리게."},
      {"speaker":"","text":"빛은 고목숲 가장 깊은 곳으로 흘러간다."},
      {"speaker":"","text":"나무 아래, 지난 학기 뿌리에서 본 것과 같은 원형 문양이 이끼에 반쯤 덮여 있다."},
      {"speaker":"","text":"숲은 잠들지 않았다. 마치 누군가의 꿈을 대신 꾸고 있는 것처럼."},
      {"speaker":"","text":"텐트 하나에서 리안의 잠꼬대가 들린다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……말뚝… 뾰족한 쪽이……"},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP06 · 가시어미 변이체 ═════════
  6: {
    brief: [
      {"speaker":"","text":"[변색된 숲] 숲 한 구역의 나무껍질이 검붉게 물들어 있다. 꽃이 계절을 무시하고 한꺼번에 피어 있다.","cut":null},
      {"speaker":"셀린","portraitId":"npc-potion","text":"이건 병도 아니고 벌레 피해도 아니야."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"마력이 식물 조직 안에 과하게 농축됐어. 넘치도록 부어 놓은 것처럼."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그렇다면 원인이 따로 있다는 뜻이군요. 숲 스스로 이만큼의 마력을 만들 수는 없으니까요."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……새소리가 없어."},
      {"speaker":"","text":"땅이 흔들린다."},
      {"speaker":"","text":"[보스 등장] 거대한 가시어미 변이체가 나무 뒤에서 모습을 드러낸다.","cut":null},
      {"speaker":"","text":"원래 가시어미는 사람 키만 한 덤불형 몬스터다. 눈앞의 것은 집 한 채만 하다."},
      {"speaker":"","text":"몸 곳곳에서 검은 가시가 쉬지 않고 자라나고, 자라자마자 부러지고, 또 자란다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"저게… 가시어미?","anim":"rian-surprise"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"아니. 원래 저 모습이 아니야."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"자라는 걸 멈출 수가 없는 거야. 저건… 고통스러운 거야.","anim":"celine-sad"},
      {"speaker":"도란","portraitId":"comp-doran","text":"진형 잡아!"},
    ],
    outro: [
      {"speaker":"","text":"[변이핵] 변이체가 쓰러진다. 검은 가시들이 땅속으로 파고들며 사라진다.","cut":null},
      {"speaker":"","text":"남은 몸은 시들지 않고, 그 자리에서 작은 꽃밭이 된다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……쓰러뜨렸는데 왜 꽃이 피어?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"이건 죽어서 흩어지는 마력이 아니야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"어딘가로… 흘러가고 있는 것처럼 보이는군요. 땅 밑으로."},
      {"speaker":"","text":"셀린이 꽃밭 한가운데서 주먹만 한 변이핵을 꺼내 봉인 주머니에 넣는다."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"이번에는 내가 직접 챙길게. 학교에 가져가서 제대로 분석해야 해."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……얘도 원래는 그냥 덤불이었겠지.","anim":"doran-think"},
      {"speaker":"","text":"아무도 대답하지 않는다. 리안이 꽃 한 송이를 꺾으려다, 그만두고 손을 거둔다."},
      {"speaker":"","text":"밤. 캠프. 모닥불 앞에서 셀린이 변이핵 분석 메모를 쓰고, 오웬은 통신 수정구로 학교에 보고한다.","cut":"ep06-a"},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"다친 사람은 없니?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"가벼운 찰과상뿐입니다. 리안 학생이 텐트에 걸려 넘어진 것 말고는요."},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"……그건 전투 부상으로 안 쳐 주마. 변이핵은 셀린 선생이 가져오도록 하렴. 학교 연구실에서 같이 보자꾸나."},
      {"speaker":"","text":"통신이 끊긴다. 리안이 모닥불 너머로 소리친다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"다 들렸거든요!"},
      {"speaker":"","text":"셀라가 웃음을 참느라 노트로 얼굴을 가린다. 노트에는 오늘 날짜와 함께 한 줄이 적혀 있다.","anim":"sella-notes"},
      {"speaker":"","text":"「쓰러진 변이체 → 꽃. 마력이 '죽지' 않는다. 어디로 가는가?」"},
    ],
  },
  // ═════════ EP07 · 고목의 문장 ═════════
  7: {
    brief: [
      {"speaker":"","text":"[고목 아래 균열] 변이체의 흔적이 흘러간 방향을 따라가면, 숲에서 가장 오래된 나무 아래 지하 통로가 나타난다.","cut":null},
      {"speaker":"","text":"통로 벽을 따라 뿌리가 혈관처럼 뻗어 있고, 뿌리마다 희미한 금빛이 맥박친다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"이건 자연적으로 생긴 게 아니야. 벽이 너무 반듯해."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"벽면의 문양을 보십시오. 모두 같은 구조입니다. 바깥에서 안쪽으로 감기는 원."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"닫힘… 봉쇄에 가까운 형태야. 뭔가를 '못 나오게' 하는 쪽."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그럼 우리가 지금 못 나오게 한 곳으로 들어가고 있는 거야?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"응."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……'응'이 이렇게 무서운 말이었나."},
      {"speaker":"","text":"[고대목 골렘] 통로 끝, 둥근 방. 벽 한가운데의 거대한 나무 형상이 눈을 뜬다.","cut":null},
      {"speaker":"","text":"이끼가 비처럼 떨어진다. 골렘이 몸을 일으키자 방 전체가 삐걱인다."},
      {"speaker":"고대목 골렘","text":"돌…려…보내라……"},
      {"speaker":"리안","portraitId":"comp-rian","text":"방금 말했지? 나무가 말했지?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"들었어. 네가 두 번 말 안 해도 돼."},
      {"speaker":"도란","portraitId":"comp-doran","text":"말할 여유는 전투 끝나고."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"저 문양… 공격용이 아닙니다. 수호 각인입니다. 저건 '지키는' 존재예요!"},
      {"speaker":"리안","portraitId":"comp-rian","text":"지키는 애가 왜 우릴 때리려 하는데요!"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"우리가 '지켜야 할 쪽'에 서 있으니까겠죠!"},
    ],
    outro: [
      {"speaker":"","text":"[마지막 문장] 골렘이 무너진다. 무릎을 꿇은 채, 마지막 힘으로 돌판 하나를 내민다.","cut":null},
      {"speaker":"","text":"돌판에는 네 개의 원과, 그 원들을 가로지르는 닫힌 문이 새겨져 있다."},
      {"speaker":"주인공","player":true,"text":"네 개의 원… 뭘 뜻하는 거지?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"아직은 알 수 없습니다. 다만 네 개 중 하나만 테두리가 금으로 덧칠되어 있군요."},
      {"speaker":"","text":"골렘의 마지막 음성. 아까보다 훨씬 작고, 거의 부탁처럼 들린다."},
      {"speaker":"고대목 골렘","text":"문을… 닫아라… 기쁨이… 새어 나간다……"},
      {"speaker":"","text":"골렘의 눈빛이 꺼진다. 방 안의 금빛 맥박이 아주 조금 약해진다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……기쁨?"},
      {"speaker":"","text":"모닥불. 세 동료가 이번 원정을 돌아본다. 불티가 별 사이로 올라간다.","cut":"ep07-a"},
      {"speaker":"리안","portraitId":"comp-rian","text":"그래도 재밌었다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"보스가 재밌었던 거겠지."},
      {"speaker":"도란","portraitId":"comp-doran","text":"다음엔 덜 위험했으면 좋겠고."},
      {"speaker":"리안","portraitId":"comp-rian","text":"근데 그 골렘… 우리 미워해서 싸운 거 아니지?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"응. 일해서 싸운 거야."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……일하다가 쓰러진 거네."},
      {"speaker":"","text":"모닥불이 탁 튄다. 아무도 한동안 말이 없다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"'기쁨이 새어 나간다.' 무섭다는 말이 아니라 기쁘다는 말인데, 왜 이렇게 무섭지.","anim":"sella-think"},
      {"speaker":"","text":"얼굴과 이름은 보여 주지 않는다.","cut":"ep07-b"},
      {"speaker":"","text":"용암 온천. 김이 자욱하다. 거대한 뿔의 그림자가 어깨까지 몸을 담그고 있다."},
      {"speaker":"","text":"옆에서 작은 날개 달린 수하가 장기판을 들고 종종걸음으로 온다."},
      {"speaker":"작은 수하","text":"폐하! 그롯 님이 또 장기에서 이기셨다고 자랑하고 다니십니다!"},
      {"speaker":"뿔의 그림자","text":"그 녀석은 말이 안 되는 곳으로 말을 옮긴단다."},
      {"speaker":"작은 수하","text":"그럼 왜 그냥 두십니까?"},
      {"speaker":"뿔의 그림자","text":"이기면 저렇게 좋아하니까."},
      {"speaker":"","text":"온천 바닥의 바위틈이 은은한 금빛으로 물든다."},
      {"speaker":"","text":"같은 순간 — 아주 먼 남쪽, 무너진 골렘의 방에서 꺼졌던 금빛 맥박이 다시 한 번, 약하게 뛴다."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP08 · 숲을 떠나 바다로 ═════════
  8: {
    brief: [
      {"speaker":"","text":"[개강] 강의실. 방학 동안 햇볕에 그을린 학생들. 루스벨만 유독 피부가 멀쩡하다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"너 방학 때 뭐 했어? 하나도 안 탔네."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"화염 특강. 불 옆에 있으면 오히려 안 타."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……그게 말이 돼?"},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"나한텐 돼."},
      {"speaker":"","text":"미르엘이 들어온다. 교탁에 조사단 보고서 다발을 내려놓는다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"방학 동안 수고했다. 조사단 보고서는 전부 읽었단다. 특히 '발견자 리안'이라고 쓴 부분이 아주 크더구나."},
      {"speaker":"","text":"교실에 웃음이 번진다. 리안이 뿌듯하게 가슴을 편다."},
      {"speaker":"","text":"수업 후, 주인공이 돌판의 탁본을 들고 교탁으로 간다."},
      {"speaker":"주인공","player":true,"text":"교수님, 이 문양을 아세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"오래된 봉인술과 닮았구나. 수호 각인 쪽 계열이야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"'닮았다'고 하시는 건, 확실하지 않다는 뜻입니까?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"기록이 부족하니까. 모르는 걸 아는 척하는 게 학자에게 제일 위험한 일이란다, 오웬."},
      {"speaker":"","text":"오웬이 고개를 끄덕인다. 존경이 섞인 끄덕임이다.","anim":"owen-think"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"이건 네가 계속 가지고 있으렴. 발견한 사람이 끝까지 보는 게 맞지."},
    ],
    outro: [
      {"speaker":"","text":"[해안 현장실습] 셀린이 다음 현장실습을 소개한다. 칠판에 물고기 그림이 그려져 있다. 생각보다 못 그렸다.","cut":null},
      {"speaker":"셀린","portraitId":"npc-potion","text":"이번 현장수업은 에르디아 해안이야. 해양 생태 조사랑 낚시 실습."},
      {"speaker":"리안","portraitId":"comp-rian","text":"바다!"},
      {"speaker":"셀린","portraitId":"npc-potion","text":"칠판 그림은 고등어야."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……저는 그걸 고양이로 봤어요."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"…다음엔 반 선생님한테 그려 달라고 할게."},
      {"speaker":"도란","portraitId":"comp-doran","text":"이번에도 보스 있는 건 아니겠지?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그런 말 하면 꼭 있어."},
      {"speaker":"","text":"반이 방수 가방을 하나씩 내민다.","anim":"van-give"},
      {"speaker":"반","portraitId":"npc-weapon","text":"장비부터 챙겨. 물은 적보다 장비를 더 자주 망가뜨린다."},
      {"speaker":"반","portraitId":"npc-weapon","text":"부서지면—"},
      {"speaker":"리안 · 셀라 · 도란","text":"돌아와서 말할게요."},
      {"speaker":"반","portraitId":"npc-weapon","text":"……그래."},
      {"speaker":"","text":"숲을 빠져나와 언덕을 넘는 주인공 시점. 숲의 녹음이 뒤로 물러나고, 화면이 한꺼번에 넓어진다.","cut":"ep08-a"},
      {"speaker":"","text":"끝없는 푸른 바다. 소금 냄새가 화면 너머로 느껴질 것처럼 바람이 분다."},
      {"speaker":"","text":"리안이 언덕 위에서 두 팔을 벌린다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"바다다아아—!"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"소리 지르면 바다가 대답해 줘?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"안 해 줘도 질러야 하는 거야, 이건."},
      {"speaker":"","text":"짧은 순간, 물결 위에 고목에서 본 원형 문양이 비친다. 아무도 보지 못한다."},
    ],
  },
  // ═════════ EP09 · 바다는 기다리는 사람에게 ═════════
  9: {
    brief: [
      {"speaker":"","text":"[어민의 부탁] 작은 선착장. 늙은 어부 토마가 텅 빈 그물을 손질하고 있다.","cut":null},
      {"speaker":"토마","text":"요즘 물고기가 깊은 곳으로만 가. 사십 년 바다에 나갔는데 이런 해는 처음이야."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"수온 변화인가요?"},
      {"speaker":"토마","text":"그랬으면 좋겠는데… 밤마다 바다 밑에서 빛이 올라와. 고기들이 그 빛 쪽으로 몰려가."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그런 얘기 들으면 더 가 보고 싶은데.","anim":"rian-laugh"},
      {"speaker":"도란","portraitId":"comp-doran","text":"그래서 네가 위험한 거야."},
      {"speaker":"토마","text":"자네 같은 젊은이를 바다가 제일 좋아하지. 데려가고 싶어서."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……농담이시죠?"},
      {"speaker":"토마","text":"반은."},
    ],
    outro: [
      {"speaker":"","text":"[폐등대] 해질 무렵, 바위곶 끝의 폐등대. 녹슨 계단이 바람에 울린다.","cut":null},
      {"speaker":"","text":"꼭대기 등실 바닥에 원형 문양이 새겨져 있다. 소금기에 반쯤 지워졌다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"여기… 숲에서 본 거랑 비슷해."},
      {"speaker":"","text":"오웬이 문양을 종이에 베낀다. 손이 빠르고 정확하다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"형태는 같지만 중심부가 다릅니다. 숲의 것은 '안으로 감기는' 원이었는데, 이건 '바깥으로 닫히는' 원입니다."},
      {"speaker":"주인공","player":true,"text":"같은 사람이 만든 걸까요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"같은 시대의 기술인 것은 분명합니다. 그 이상은… 아직 모르는 게 너무 많습니다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"근데 이 등대, 왜 버려진 거예요?"},
      {"speaker":"토마","text":"불을 켜도, 바다 밑 빛이 더 밝아서. 배들이 자꾸 그쪽으로 갔거든."},
      {"speaker":"","text":"밤. 해안 마을의 집들이 하나둘 창문을 닫는다. 덧문 닫히는 소리가 파도 소리를 따라 번진다.","cut":"ep09-a"},
      {"speaker":"","text":"수평선 아래에서 푸른빛이 솟는다. 한 번. 두 번. 세 번."},
      {"speaker":"","text":"빛이 솟을 때마다 바다 전체가 숨을 들이쉬는 것처럼 조용해진다."},
      {"speaker":"토마","text":"저건… 다시 시작됐군. 내 할아버지 때 이후 처음이야."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"숲이 이상해진 것도 이번 봄부터. 바다도 이번 해부터.","anim":"sella-think"},
      {"speaker":"도란","portraitId":"comp-doran","text":"같이 시작됐다는 거네."},
      {"speaker":"","text":"카메라가 물속으로 내려간다. 빛을 따라 아래로, 더 아래로."},
      {"speaker":"","text":"해저 깊은 곳에 거대한 돌문이 짧게 보인다. 문 표면의 원형 홈 하나가 빛에 맞춰 떨리고 있다."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP10 · 중간고사, 그리고 해저 유적 ═════════
  10: {
    brief: [
      {"speaker":"","text":"[중간고사] 오웬이 감독관으로 들어와 시험지를 나눠 준다. 교실에 종이 넘기는 소리만 가득하다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이번 시험은 단순 암기만으로 풀 수 없습니다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그 말은 어렵다는 뜻이네요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"정확합니다. 첫 문제부터 맞히셨군요."},
      {"speaker":"","text":"실패해도 스토리는 진행되며 보정 과제가 열린다."},
      {"speaker":"","text":"시험 후 복도. 결과 게시판 앞."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"화염 실기 1등. 또."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……난 역사에서 1등 했거든."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"네가? 역사를?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"찍었는데 다 맞았어."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그건 1등이 아니라 사고야."},
      {"speaker":"","text":"[얕은 해저 조사] 해안 실습. 수중 호흡 물약을 마시고 얕은 바다로 들어간다.","cut":null},
      {"speaker":"","text":"물속은 조용하다. 햇빛이 물결 무늬로 모래 위에 흔들린다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"잠깐. 저 돌은 자연석이 아니야."},
      {"speaker":"","text":"주인공이 조사하면, 모래 밑에서 반듯한 석재와 계단 일부가 드러난다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"문이 있었던 흔적 같아. 계단이 아래로 이어져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"바다 밑에 건물이 있었다고? 누가 바다 밑에 집을 지어?"},
      {"speaker":"셀린","portraitId":"npc-potion","text":"처음부터 바다 밑은 아니었을 거야. 땅이었던 곳이 가라앉은 거지."},
    ],
    outro: [
      {"speaker":"","text":"[오웬의 판독] 선착장으로 돌아와 젖은 탁본을 말린다. 오웬이 기호 하나하나를 손가락으로 짚어 간다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"울토르에서 쓰는 문자보다 오래됐습니다. 지금 왕국 문자의 조상보다도 오래됐을 겁니다."},
      {"speaker":"주인공","player":true,"text":"읽을 수 있어요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"지금은 아닙니다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"부끄러운 고백이지만, 사서 생활 이십 년 만에 '못 읽겠다'는 말을 이렇게 자주 하게 된 건 처음입니다."},
      {"speaker":"","text":"이 '못 읽는 문자'는 훗날 설원의 석비와 연결한다."},
      {"speaker":"","text":"해저 계단 끝. 주인공이 돌문 표면에 손을 대자, 네 개의 원형 홈이 잠깐 빛난다.","cut":"ep10-a"},
      {"speaker":"","text":"그중 하나 — 숲의 돌판에서 금으로 덧칠되어 있던 바로 그 자리 — 가 가장 밝다."},
      {"speaker":"","text":"물결이 거꾸로 흐르는 것처럼 보이고, 문이 아주 미세하게 떨린다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"뭔가… 아직 살아 있어."},
      {"speaker":"","text":"문은 열리지 않는다. 떨림이 천천히 가라앉는다."},
    ],
  },
  // ═════════ EP11 · 파도 아래 잠든 것 ═════════
  11: {
    brief: [
      {"speaker":"","text":"[학기말] 방파제 위. 학기말 시험이 끝나고, 일행이 다리를 바다 쪽으로 늘어뜨리고 앉아 있다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"한 학기 진짜 길었다. 그래도 많이 배웠네."},
      {"speaker":"주인공","player":true,"text":"근데 유적 문제는 아직 아무것도 모르겠어요."},
      {"speaker":"도란","portraitId":"comp-doran","text":"숲도 모르고, 바다도 모르고."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그래서 이번엔 더 아래로 가는 거야. 계단이 끝나는 곳까지.","anim":"sella-think"},
      {"speaker":"셀린","portraitId":"npc-potion","text":"그 전에 이것부터. 수중 호흡 물약 두 배 농도. 맛은… 각오하렴."},
      {"speaker":"","text":"리안이 한 모금 마시고 얼굴을 구긴다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……바다 맛이에요."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"바다 들어가는데 바다 맛이면 딱 좋지."},
      {"speaker":"","text":"[해안 수호수] 해저 계단 아래, 유적 입구. 산호로 뒤덮인 거대한 거북 형상의 수호수가 입구를 막고 있다.","cut":null},
      {"speaker":"","text":"수호수는 일행을 보자 공격하지 않고, 천천히 몸을 돌려 입구를 더 단단히 가린다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이건 우리 못 들어가게 막는 거지?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"아마 지키는 거겠지. 숲의 골렘처럼."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"죽이지 말고 제압하자. 저 애도 일하는 중이야."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……요즘 우리가 싸우는 애들 다 일하는 중이네."},
    ],
    outro: [
      {"speaker":"","text":"[첫 파편] 수호수가 천천히 물러나 유적 깊은 어둠 속으로 사라진다.","cut":null},
      {"speaker":"","text":"자리에 남은 것은 손바닥만 한 인장 파편 하나. 표면에 원의 일부가 새겨져 있다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"숲에서 본 것과 같은 계열이야. 온도도 같아. 따뜻해."},
      {"speaker":"도란","portraitId":"comp-doran","text":"그럼 서로 다른 곳에서 같은 일이 생기고 있다는 거네."},
      {"speaker":"리안","portraitId":"comp-rian","text":"숲이랑 바다가 무슨 상관인데?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그걸 모르니까 무서운 거야."},
      {"speaker":"","text":"화면이 둘로 갈라진다. 왼쪽은 에르디아 숲 깊은 곳의 원형 문양, 오른쪽은 해저 돌문의 원형 홈.","cut":"ep11-a"},
      {"speaker":"","text":"둘이 동시에 빛난다. 빛줄기가 서로를 향해 뻗어 — 연결되려는 순간, 끊어진다."},
      {"speaker":"","text":"그리고 아주 잠깐, 두 빛줄기가 같은 방향을 가리킨다. 북쪽."},
      {"speaker":"","text":"멀리 떨어진 두 장소에서, 같은 무언가가 같은 쪽을 바라보고 있었다."},
    ],
  },
  // ═════════ EP12 · 겨울 바다의 불빛 ═════════
  12: {
    brief: [
      {"speaker":"","text":"[아틀란티스 도착] 물 위에 걸쳐 지어진 하얀 도시. 수로마다 작은 배가 오가고, 다리 위에서 상인들이 생선을 외친다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"와… 진짜 도시가 물 위에 떠 있네.","anim":"rian-surprise"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"떠 있는 건 아니고, 수로와 건축이 함께 설계된 도시입니다. 지반 아래로 기둥이 삼천 개쯤 박혀 있죠."},
      {"speaker":"리안","portraitId":"comp-rian","text":"사서님은 감동을 숫자로 하세요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"숫자를 알면 감동이 두 배가 됩니다. 삼천 개입니다, 리안 학생. 삼천 개."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……두 배 됐어.","anim":"doran-think"},
      {"speaker":"","text":"[방학 생활] 낚시, 해양 채집, 상인 심부름, 주민 도움 퀘스트.","cut":null},
      {"speaker":"","text":"선술집 주인이 일행에게 생선 수프를 공짜로 내준다. 지난 학기 해안 마을에서 토마를 도운 소문이 여기까지 퍼졌다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"이번 방학은 좀 여유롭네."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그렇게 말하면 꼭 일이 생겨."},
      {"speaker":"리안","portraitId":"comp-rian","text":"넌 맨날 그 말 하더라."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그리고 맨날 맞지."},
      {"speaker":"","text":"[밤의 불빛] 밤. 선착장. 밤바다에서 거대한 푸른빛이 솟는다. 지난번 해안에서 본 것보다 훨씬 크다.","cut":null},
      {"speaker":"","text":"도시 사람들이 일제히 등불을 끄고 고개를 돌린다."},
      {"speaker":"주민","text":"저 빛은 보지 않는 게 좋아."},
      {"speaker":"주인공","player":true,"text":"왜요?"},
      {"speaker":"주민","text":"오래전부터 저 빛이 나타난 해엔 꼭 사고가 났거든. 어른들은 '바다 밑 재앙이 뒤척인다'고 했어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"재앙이 뒤척여요? 자다가?"},
      {"speaker":"주민","text":"그래. 그러니까 깨우지 말라고."},
    ],
    outro: [
      {"speaker":"","text":"카메라가 수면 아래로 내려간다. 거대한 광원이 해저 깊은 곳에서 맥박친다.","cut":"ep12-a"},
      {"speaker":"","text":"그 아래, 반쯤 모래에 잠긴 돌문. 문의 네 홈 중 하나가 광원과 같은 박자로 깜빡인다."},
      {"speaker":"","text":"용암이 흐르는 마을 외곽의 작은 밭. 화산재 흙에 무언가가 줄지어 심겨 있다.","cut":"ep12-b"},
      {"speaker":"","text":"거대한 뿔의 그림자가 쪼그려 앉아 새싹 하나를 들여다본다. 뒤에서 덩치 큰 수하가 물뿌리개를 들고 있다."},
      {"speaker":"덩치 큰 수하","text":"폐하, 그건 잡초입니다."},
      {"speaker":"뿔의 그림자","text":"알고 있다."},
      {"speaker":"덩치 큰 수하","text":"……그럼 왜 물을 주라고 하십니까?"},
      {"speaker":"뿔의 그림자","text":"여기까지 와서 자란 게 기특하지 않느냐."},
      {"speaker":"","text":"그녀가 손끝으로 새싹을 건드린다. 새싹이 쑥, 손가락 한 마디만큼 자란다."},
      {"speaker":"","text":"덩치 큰 수하가 물뿌리개를 떨어뜨린다."},
      {"speaker":"덩치 큰 수하","text":"폐하. 방금……"},
      {"speaker":"뿔의 그림자","text":"……그러게. 방금."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP13 · 해파리 여왕 ═════════
  13: {
    brief: [
      {"speaker":"","text":"[심해 진입] 빛이 닿지 않는 깊이. 일행의 수정구 불빛만이 주변을 비춘다.","cut":null},
      {"speaker":"","text":"가끔 거대한 무언가가 불빛 바깥을 스쳐 지나간다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"돌아갈 길은 반드시 표시해 두십시오. 반드시."},
      {"speaker":"리안","portraitId":"comp-rian","text":"사서님 무서우세요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"저는 지금 매우 침착합니다. 단지 이 깊이에서 길을 잃으면 도서관 반납 기한을 영영 못 지킬 뿐입니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……무서우신 거네."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이번엔 진짜 아래로 간다."},
      {"speaker":"","text":"[해파리 여왕] 거대한 반투명 해파리가 어둠 속에서 피어오른다. 몸 안에서 수천 개의 작은 빛이 별처럼 흐른다.","cut":null},
      {"speaker":"","text":"주변의 작은 해파리들이 여왕을 향해 빛을 흘려보낸다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……예쁘다.","anim":"doran-think"},
      {"speaker":"리안","portraitId":"comp-rian","text":"지금 그 말 할 때야?!"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"저 움직임… 마력진이랑 같아. 여왕 혼자가 아니라, 주변 전체가 하나의 진을 그리고 있어."},
      {"speaker":"","text":"여왕의 촉수가 휘둘러질 때마다 빛의 궤적이 하나의 문양을 그려 간다. 해저 돌문의 원형 홈과 같은 모양이다."},
    ],
    outro: [
      {"speaker":"","text":"[전투 후] 여왕이 빛을 잃고 천천히 가라앉는다. 작은 해파리들이 흩어진다.","cut":null},
      {"speaker":"","text":"여왕이 그리던 문양이 미완성인 채로 물속에 남아 서서히 흐려진다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이건 생태 이상이 아닙니다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"여왕은 문을 '열려고' 한 게 아닙니다. 문이 먼저 흔들렸고, 여왕은 그걸 다시 잠그려고 진을 그리고 있었던 겁니다."},
      {"speaker":"주인공","player":true,"text":"그럼 문을 흔드는 건 누군데요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……문 안쪽, 혹은 문 너머 어딘가. 무언가가 깨어나고 있습니다."},
      {"speaker":"","text":"돌문이 아주 조금 열렸다가, 스스로 닫힌다.","cut":"ep13-a"},
      {"speaker":"","text":"문틈 너머로 아주 짧게 — 어둠이 아니라 따뜻한 빛이 새어 나온다. 그 빛은 어딘가 슬퍼 보인다."},
    ],
  },
  // ═════════ EP14 · 암초왕의 기억 ═════════
  14: {
    brief: [
      {"speaker":"","text":"[암초왕의 영역] 심해 유적의 중심. 산호와 바위가 엉겨 붙은 왕좌 위에 거대한 암초의 거인이 앉아 있다.","cut":null},
      {"speaker":"","text":"거인은 일어나지 않는다. 다만 눈을 뜬다."},
      {"speaker":"암초왕","text":"인간은 또 문을 찾아왔군."},
      {"speaker":"리안","portraitId":"comp-rian","text":"또 말한다!","anim":"rian-surprise"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"요즘 말하는 애들 많아. 적응해."},
      {"speaker":"주인공","player":true,"text":"우리는 이 문이 뭔지 알고 싶을 뿐이에요."},
      {"speaker":"암초왕","text":"알면, 부르게 된다. 부르면, 또 빼앗으러 온다."},
      {"speaker":"암초왕","text":"그 이름을 부르지 마라. 이번에는 내가 지킨다."},
    ],
    outro: [
      {"speaker":"","text":"[보스전] 암초왕이 일어선다. 그러나 공격은 대부분 일행을 문에서 '떼어 놓는' 동작이다.","cut":null},
      {"speaker":"","text":"HP가 줄어들수록 암초왕은 공격하기보다 등 뒤의 문을 몸으로 가린다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……이 사람, 우리 죽이려는 게 아니야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"알고 있습니다. 알고 있어서 더 괴롭군요."},
      {"speaker":"","text":"[기억의 파편] 암초왕이 무너지며 몸에서 빛의 파편이 흩어진다. 파편 하나가 주인공에게 닿는 순간, 시야가 바뀐다.","cut":null},
      {"speaker":"","text":"— 오래전의 바닷가 도시. 지금의 아틀란티스와 닮았지만 훨씬 오래된."},
      {"speaker":"","text":"인간과, 뿔이 달린 이들과, 비늘이 있는 이들이 같은 시장에서 생선을 고른다."},
      {"speaker":"","text":"높은 계단 위에서 왕관을 쓴 누군가가 그 시장을 내려다본다. 얼굴은 빛에 가려 보이지 않는다."},
      {"speaker":"","text":"그녀가 웃는다. 아이 하나가 손을 흔들고, 그녀도 손을 흔들어 준다."},
      {"speaker":"","text":"장면이 일그러진다. 같은 계단 위, 사슬. 의식. 네 개의 빛이 한 사람의 몸에서 뜯겨 나간다."},
      {"speaker":"","text":"비명은 들리지 않는다. 다만 바다가 한꺼번에 차가워진다."},
      {"speaker":"","text":"시야가 돌아온다. 주인공의 손이 떨리고 있다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"야, 괜찮아? 너 지금 울어."},
      {"speaker":"주인공","player":true,"text":"……어. 왜 그러지."},
      {"speaker":"","text":"[이름] 문 옆 벽면. 고대문자 위로, 날카로운 정으로 덧새긴 다른 글자들이 겹쳐 있다.","cut":null},
      {"speaker":"","text":"오웬이 손전등을 비추다가 멈춘다. 덧새긴 쪽은 — 읽을 수 있다. 오래된 왕국 공용문자다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"마왕… 모… 르… 스."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"'재앙의 왕 모르스, 이곳에 봉하다.'"},
      {"speaker":"주인공","player":true,"text":"모르스?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"교과서에만 나오던 이름을, 이런 곳에서 직접 확인하는 건 처음입니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"근데 이상해. 아래 글자는 고대문자고, 위 글자는 우리 문자의 옛날 형태잖아.","anim":"sella-think"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그럼 이 이름은… 원래 여기 쓰여 있던 게 아니라, 누가 나중에 와서 위에 덧쓴 거야."},
      {"speaker":"","text":"정적. 물방울 떨어지는 소리."},
      {"speaker":"도란","portraitId":"comp-doran","text":"아래에는 뭐라고 쓰여 있었는데?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……읽을 수 없습니다. 아무도."},
      {"speaker":"","text":"화면에 해저에서 본 기억 속 왕의 실루엣과, 학교 교과서 속 '마왕 모르스' 삽화가 겹친다.","cut":"ep14-a"},
      {"speaker":"","text":"기억 속 왕은 아이에게 손을 흔들고 있다. 교과서 속 마왕은 불타는 도시 위에서 포효하고 있다."},
      {"speaker":"","text":"같은 왕관. 같은 뿔. 정반대의 얼굴."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"같은 인물인데… 왜 이렇게 다르지."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"기억이 틀린 걸까. 아니면 교과서가—"},
      {"speaker":"","text":"독백이 끊긴다. 오웬이 스스로 생각을 멈춘다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"근데 아까 그 기억에서… 시장 생선 엄청 싱싱해 보이지 않았어?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"……봤어."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"너희 둘은 진짜."},
      {"speaker":"","text":"셋이 피식 웃는다. 웃음이 오래가지 않는다."},
    ],
  },
  // ═════════ EP15 · 돌아온 학생, 남겨진 질문 ═════════
  15: {
    brief: [
      {"speaker":"","text":"[개강] 본관 계단. 유나가 2학년 배지를 단 후배들을 맞는다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"2학년부터는 수업이 좀 더 전문적으로 변할 거야."},
      {"speaker":"리안","portraitId":"comp-rian","text":"1학년도 충분히 힘들었는데요."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"그래서 2학년이지. 힘든 걸 버틴 사람한테 더 힘든 걸 주는 게 학교거든."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……그거 학교 홍보 문구로 쓰면 안 되겠다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"난 2학년 수업 미리 다 봤어. 별거 없더라."},
      {"speaker":"리안","portraitId":"comp-rian","text":"저 말 1학년 때도 했다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"1학년 때도 맞았지."},
    ],
    outro: [
      {"speaker":"","text":"[모르스의 이름] 역사 수업. 미르엘의 강의. 오웬이 해안에서 베껴 온 기록을 들고 청강하러 들어와 있다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"인마대전. 오백 년 전, 마왕 모르스가 인간 왕국을 침공하며 시작된 전쟁이지."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"교수님. 해안 심해 유적에서 그 이름을 직접 확인했습니다. 다만 그 이름은 원래 문장 위에 덧새겨져 있었습니다."},
      {"speaker":"","text":"교실이 조용해진다."},
      {"speaker":"주인공","player":true,"text":"그리고… 거기서 본 기억 속의 왕은, 교과서랑 달랐어요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"역사는 보는 사람에 따라 조금씩 다르게 보이는 법이지."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"하지만 날짜까지 달라집니다. 해안의 기록과 공식 연대표가 삼 년이나 어긋납니다."},
      {"speaker":"","text":"정적. 학생들이 미르엘의 눈치를 본다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"좋다. 그럼 숙제로 하자꾸나.","anim":"mirel-laugh"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"두 기록이 다르면, 어느 쪽이 먼저 쓰였는지부터 확인하렴. 누가, 언제, 왜 썼는지. 그게 역사학의 첫걸음이란다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……질문했더니 숙제가 생겼어."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"오웬 사서님 탓이야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"역사학의 첫걸음입니다."},
      {"speaker":"","text":"밤의 도서관. 오웬 혼자 공식 역사서 『울토르 왕국사』 원본을 펼친다.","cut":"ep15-a"},
      {"speaker":"","text":"인마대전 장에서 손이 멈춘다. 그 장만 종이 색이 미세하게 다르다."},
      {"speaker":"","text":"제본 실을 살펴보면 — 그 몇 장만 나중에 다시 꿰맨 흔적이 있다."},
      {"speaker":"","text":"장의 끝, 작은 붉은 도장: 「왕립 기록원 — 교정필」."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"교정… 무엇을 바로잡았다는 거지."},
      {"speaker":"","text":"오웬이 도장의 날짜를 확인한다. 삼백 년 전.","anim":"owen-think"},
      {"speaker":"","text":"그는 안경을 벗고, 오래 눈을 감는다."},
      {"speaker":"","text":"……이건 학생들에게 아직 보여 주지 말자."},
      {"speaker":"","text":"의심은 '오래전 누군가'를 향한다. 미르엘은 등장하지 않는다."},
    ],
  },
  // ═════════ EP16 · 기록이 다르게 쓰여 있다 ═════════
  16: {
    brief: [
      {"speaker":"","text":"[문헌 대조] 도서관 열람실. 오웬이 두 판본을 책상에 나란히 펼친다. 셀라가 숙제를 핑계로 와 있다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"같은 사건인데 날짜가 세 군데서 다릅니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"필사 오류?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"한 번이면 그렇겠죠."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그런데 세 번 다, 모르스에게 불리한 쪽으로 틀렸습니다. 오류는 보통 그렇게 한쪽으로만 나지 않습니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……누가 일부러 고쳤다는 거네요.","anim":"sella-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그렇게 말하기엔 아직 증거가 부족합니다. 하지만 그렇게 생각하지 않기엔 우연이 너무 많군요."},
    ],
    outro: [
      {"speaker":"","text":"[카엘의 지도] 빙결 실습실. 조교 카엘이 학생들의 보고서를 쌓아 두고 낡은 지도 한 장을 꺼낸다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"이거. 스톰헤이븐 쪽 지도."},
      {"speaker":"주인공","player":true,"text":"교과서에 없는 길이 있네요?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"있어. 내 고향이 거기 아래 마을이야. 어릴 때 할머니가 '하늘로 가는 옛길'이라고 불렀지."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"근데 왜 공식 지도엔 없어요?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"그래서 확인하려는 거다. …보고서는 다들 냈지?"},
      {"speaker":"주인공","player":true,"text":"……내일까지는요."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"오늘까지야."},
      {"speaker":"","text":"[미르엘과의 대화] 복도. 미르엘이 주인공과 셀라를 불러 세운다. 손에 두 사람의 숙제가 들려 있다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"숙제 잘 봤다. 셀라, 날짜 대조표는 교수들보다 낫더구나."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……감사합니다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"다만, 카엘 조교가 스톰헤이븐 옛길 이야기를 했다지?"},
      {"speaker":"주인공","player":true,"text":"네. 직접 가 보고 싶어요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"학생이 혼자 너무 깊이 들어갈 길은 아니란다. 그 길은 바람이 사람을 날려 보내는 곳이야."},
      {"speaker":"주인공","player":true,"text":"그럼 교수님은 반대세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"반대가 아니라 걱정이지. 정식으로 가는 방법을 찾아보자꾸나. 그건 내가 도와줄 수 있으니.","anim":"mirel-laugh"},
      {"speaker":"","text":"그녀는 걱정하는 교수처럼 보인다. 그리고 실제로, 다음 막에서 길을 열어 준다."},
      {"speaker":"","text":"오웬이 빛 수정구로 오래된 문서의 지워진 줄을 비춘다.","anim":"owen-think","cut":"ep16-a"},
      {"speaker":"","text":"긁어낸 자국 사이로, 단 한 글자만 살아남아 있다. 「왕」."},
      {"speaker":"","text":"그 옆 여백에도 같은 붉은 도장이 찍혀 있다. 「왕립 기록원 — 교정필」."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"마왕이 아니라… 왕."},
    ],
  },
  // ═════════ EP17 · 하늘에서 내려온 초대 ═════════
  17: {
    brief: [
      {"speaker":"","text":"[기말시험] 종합 실기: 영창 암기 → 리듬 타이밍 → 원소 실전.","cut":null},
      {"speaker":"","text":"시험 직전, 대기실. 리안이 손바닥에 영창을 적다가 도란에게 들킨다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"그거 땀 나면 번져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……'불꽃이여, 나의 ㅁ…ㄴ…'"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"시험은 너를 평가하는 자리가 아니라, 다음에 무엇을 배워야 하는지 알려 주는 자리란다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"리안은 다음에 손 씻는 법부터 배우면 되겠구나."},
    ],
    outro: [
      {"speaker":"","text":"[초대장] 시험이 끝난 뒤. 카엘이 은빛 봉랍으로 봉인된 편지를 들고 온다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"스톰헤이븐 연구진이 정식으로 초청했어. 천공 신전 자료 열람 허가."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"천공 신전 기록 보관소군요. 이건 왕국 학자들도 평생 한 번 들어가기 힘든 곳입니다.","anim":"owen-surprise"},
      {"speaker":"리안","portraitId":"comp-rian","text":"그런 데를 우리가 어떻게?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"교장 선생님이 추천서를 써 주셨다. 직접."},
      {"speaker":"","text":"일행이 서로를 본다. 지난번 \"도와줄 수 있으니\"라던 말이 떠오른다."},
      {"speaker":"","text":"[승인] 교장실. 미르엘이 원정 계획서에 서명한다. 망설임이 없다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"좋아. 다녀오렴."},
      {"speaker":"주인공","player":true,"text":"교수님도 같이 가세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"나는 학교를 지켜야지. 교장이 방학마다 자리를 비우면 학교가 무너진단다. …농담이 아니라, 진짜로 결계가 무너져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……진짜요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"반쯤은.","anim":"mirel-laugh"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"대신 결과는 꼭 내게 보고하렴. 너희가 찾은 걸 제일 먼저 듣고 싶구나."},
      {"speaker":"","text":"다정하고, 기대에 찬 목소리다."},
      {"speaker":"","text":"밤하늘. 기숙사 옥상에서 일행이 하늘을 올려다본다.","cut":"ep17-a"},
      {"speaker":"","text":"구름이 갈라지며 아주 먼 곳에 거대한 신전의 실루엣이 잠깐 나타났다 사라진다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……저기까지 걸어가는 거야?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"반은 걸어서, 반은 날아서. 멀미약 챙겨."},
      {"speaker":"","text":"바다 아래에서 찾은 문은, 하늘 위로 이어져 있었다."},
    ],
  },
  // ═════════ EP18 · 방학은 조금 천천히 ═════════
  18: {
    brief: [
      {"speaker":"","text":"[동아리] 학교 게시판. 여름 동아리 모집 공고가 빽빽하다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"이번 여름은 네가 하고 싶은 걸 해 봐."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"2학년부터는 다들 진로가 조금씩 보이기 시작하거든. 그 전에 좋아하는 걸 하나쯤 찾아 둬."},
      {"speaker":"리안","portraitId":"comp-rian","text":"'용암 요리 동아리'? 이거다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그거 작년에 실습실 태워서 폐부됐어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그럼 왜 아직 붙어 있어?"},
      {"speaker":"유나","portraitId":"comp-yuna","text":"……부장이 졸업을 안 했거든."},
    ],
    outro: [
      {"speaker":"","text":"[개인공간] 주인공의 기숙사 방을 꾸민다. 동료들이 각자 가구를 들고 들이닥친다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"이거 놓자. 멋있잖아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"공간 낭비야. 그리고 그거 눈이 따라와."},
      {"speaker":"도란","portraitId":"comp-doran","text":"그래도 이건 하나쯤 있으면 좋겠는데."},
      {"speaker":"리안","portraitId":"comp-rian","text":"왜 도란 거만 바로 통과야?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"눈이 안 따라오니까."},
      {"speaker":"","text":"생활 콘텐츠 비중을 높인다(하우징·요리·낚시·제작)."},
      {"speaker":"","text":"[여름 산책] 해 질 녘 호숫가. 유나와 주인공 둘이 걷는다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"모험할 때는 다음 목적지만 보게 되잖아."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"가끔은 지금 옆에 있는 사람도 봐. 졸업하고 나면, 이 길을 같이 걷던 애들이 제일 보고 싶어지더라."},
      {"speaker":"주인공","player":true,"text":"선배도 졸업 안 했잖아요."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"미리 아는 거야. 선배니까.","anim":"yuna-laugh"},
      {"speaker":"","text":"교정에 작은 여름 축제. 등불, 노점, 하늘로 올라가는 마법 불꽃.","cut":"ep18-a"},
      {"speaker":"","text":"루스벨과 리안이 불꽃 쏘아 올리기 대결을 한다. 둘 다 점점 크게 쏘다가, 마지막 불꽃이 공중에서 부딪쳐 하트 모양이 된다."},
      {"speaker":"","text":"주변 학생들이 환호한다. 둘은 동시에 얼굴이 시뻘게진다."},
      {"speaker":"루스벨 · 리안","text":"이건 무효야!"},
      {"speaker":"","text":"웃음소리 너머, 솜사탕 노점 앞. 미르엘이 솜사탕을 받아 들다가 학생들과 눈이 마주친다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"……교장도 축제는 즐긴단다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"교수님 입에 설탕 묻었어요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"보고서에는 쓰지 말렴."},
    ],
  },
  // ═════════ EP19 · 마법 동아리 합동 실습 ═════════
  19: {
    brief: [
      {"speaker":"","text":"[합동 실습] 훈련장. 카엘이 학생들을 둘씩 짝짓는다. 리안과 루스벨이 같은 조가 된다.","cut":null},
      {"speaker":"리안 · 루스벨","text":"조교님, 바꿔 주세요."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"안 돼. 오늘은 속성의 세기가 아니라, 서로의 타이밍을 본다."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"제일 안 맞는 둘이 맞추면, 나머지는 쉽다."},
    ],
    outro: [
      {"speaker":"","text":"[빛과 어둠의 개념] 실습 자료 마지막 장에 교육과정 밖의 도식이 끼어 있다. 다섯 개의 원 — 화염·빙결·대지, 그리고 빛과 어둠.","cut":null},
      {"speaker":"셀라","portraitId":"comp-sella","text":"이건 빛과 어둠 계열이네. 우리 과정엔 없는 거잖아요."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"3학년 심화 과정 자료가 섞여 들어갔네. 연구 단계다."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"나 이거 조금 배웠어. 빛은 치유랑 보호, 그리고… 감춰진 걸 드러내는 쪽."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"감춰진 걸 드러낸다…… 지워진 글자 같은 것도요?"},
      {"speaker":"유나","portraitId":"comp-yuna","text":"글쎄? 그건 성녀님 정도는 돼야 할걸."},
      {"speaker":"","text":"[학생 토론] 실습 후, 그늘에 앉은 일행.","cut":null},
      {"speaker":"도란","portraitId":"comp-doran","text":"모든 상황에 강한 속성은 없는 것 같아."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그러니까 결국 자기 장점을 잘 쓰는 게 중요하다는 거지."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……아까 네 번째. 네 타이밍 나쁘지 않았어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"어? 어… 너도."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"적어 둬야겠다. 역사적인 날이야.","anim":"sella-think"},
      {"speaker":"도란","portraitId":"comp-doran","text":"날짜 틀리게 적지 마. 요즘 그거 민감해."},
      {"speaker":"","text":"수업이 끝난 뒤. 카엘이 섞여 들어간 3학년 자료를 보관함에 넣고 자물쇠를 채운다.","cut":"ep19-a"},
      {"speaker":"","text":"문서 맨 아래 귀퉁이에 「천공 신전 기록 사본 — 2학년 2학기 열람 예정」이라는 메모가 보인다."},
      {"speaker":"카엘 조교(혼잣말)","portraitId":"npc-kael","text":"……하늘로 가면 결국 보게 될 거다."},
    ],
  },
}

export const CUTSCENES_GEN: CutsceneDef[] = [
  {"id":"ep05-a","scene":"EP05 [CUTSCENE 05-A] 새벽의 고목숲","full":false,"shot":"야영지의 불이 꺼진 뒤, 카메라가 숲 위로 떠오른다. 뿌리 사이로 금빛 섞인 검은빛이 하나씩 점멸한다. 반딧불이처럼, 그러나 반딧불이보다 느리게. 빛은 고목숲 가장 깊은 곳으로 흘러간다. 나무 아래, 지난 학기 뿌리에서 본 것과 같은 원형 문양이 이끼에 반쯤 덮여 있다. 텐트 하나에서 리안의 잠꼬대가 들린다. 화면 암전.","refs":["리안 삼면도.jpg","스토리 NPC 일러스트.png"]},
  {"id":"ep06-a","scene":"EP06 [CUTSCENE 06-A] 모닥불과 편지","full":false,"shot":"밤. 캠프. 모닥불 앞에서 셀린이 변이핵 분석 메모를 쓰고, 오웬은 통신 수정구로 학교에 보고한다. 통신이 끊긴다. 리안이 모닥불 너머로 소리친다. 셀라가 웃음을 참느라 노트로 얼굴을 가린다. 노트에는 오늘 날짜와 함께 한 줄이 적혀 있다. 「쓰러진 변이체 → 꽃. 마력이 '죽지' 않는다. 어디로 가는가?」","refs":["리안 삼면도.jpg","전투 NPC 셀라 삼면도.png","스토리 NPC 일러스트.png"]},
  {"id":"ep07-a","scene":"EP07 [CUTSCENE 07-A] 방학 마지막 밤","full":false,"shot":"모닥불. 세 동료가 이번 원정을 돌아본다. 불티가 별 사이로 올라간다. 모닥불이 탁 튄다. 아무도 한동안 말이 없다.","refs":[]},
  {"id":"ep07-b","scene":"EP07 [INTERLUDE 07-B] 같은 시각, 화산지대 (막간)","full":true,"shot":"용암 온천. 김이 자욱하다. 거대한 뿔의 그림자가 어깨까지 몸을 담그고 있다. 옆에서 작은 날개 달린 수하가 장기판을 들고 종종걸음으로 온다. 온천 바닥의 바위틈이 은은한 금빛으로 물든다. 같은 순간 — 아주 먼 남쪽, 무너진 골렘의 방에서 꺼졌던 금빛 맥박이 다시 한 번, 약하게 뛴다. 화면 암전.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png"]},
  {"id":"ep08-a","scene":"EP08 [CUTSCENE 08-A] 바다 전환","full":false,"shot":"숲을 빠져나와 언덕을 넘는 주인공 시점. 숲의 녹음이 뒤로 물러나고, 화면이 한꺼번에 넓어진다. 끝없는 푸른 바다. 소금 냄새가 화면 너머로 느껴질 것처럼 바람이 분다. 리안이 언덕 위에서 두 팔을 벌린다. 짧은 순간, 물결 위에 고목에서 본 원형 문양이 비친다. 아무도 보지 못한다.","refs":["리안 삼면도.jpg"]},
  {"id":"ep09-a","scene":"EP09 [CUTSCENE 09-A] 겨울 바다의 전조","full":false,"shot":"밤. 해안 마을의 집들이 하나둘 창문을 닫는다. 덧문 닫히는 소리가 파도 소리를 따라 번진다. 수평선 아래에서 푸른빛이 솟는다. 한 번. 두 번. 세 번. 빛이 솟을 때마다 바다 전체가 숨을 들이쉬는 것처럼 조용해진다. 카메라가 물속으로 내려간다. 빛을 따라 아래로, 더 아래로. 해저 깊은 곳에 거대한 돌문이 짧게 보인다. 문 표면의 원형 홈 하나가 빛에 맞춰 떨리고 있다. 화면 암전.","refs":[]},
  {"id":"ep10-a","scene":"EP10 [CUTSCENE 10-A] 수면 아래의 문","full":false,"shot":"해저 계단 끝. 주인공이 돌문 표면에 손을 대자, 네 개의 원형 홈이 잠깐 빛난다. 그중 하나 — 숲의 돌판에서 금으로 덧칠되어 있던 바로 그 자리 — 가 가장 밝다. 물결이 거꾸로 흐르는 것처럼 보이고, 문이 아주 미세하게 떨린다. 문은 열리지 않는다. 떨림이 천천히 가라앉는다.","refs":[]},
  {"id":"ep11-a","scene":"EP11 [CUTSCENE 11-A] 파도 아래 잠든 것","full":false,"shot":"화면이 둘로 갈라진다. 왼쪽은 에르디아 숲 깊은 곳의 원형 문양, 오른쪽은 해저 돌문의 원형 홈. 둘이 동시에 빛난다. 빛줄기가 서로를 향해 뻗어 — 연결되려는 순간, 끊어진다. 그리고 아주 잠깐, 두 빛줄기가 같은 방향을 가리킨다. 북쪽.","refs":[]},
  {"id":"ep12-a","scene":"EP12 [CUTSCENE 12-A] 겨울 바다의 불빛","full":false,"shot":"카메라가 수면 아래로 내려간다. 거대한 광원이 해저 깊은 곳에서 맥박친다. 그 아래, 반쯤 모래에 잠긴 돌문. 문의 네 홈 중 하나가 광원과 같은 박자로 깜빡인다.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep12-b","scene":"EP12 [INTERLUDE 12-B] 같은 시각, 화산지대 (막간)","full":true,"shot":"용암이 흐르는 마을 외곽의 작은 밭. 화산재 흙에 무언가가 줄지어 심겨 있다. 거대한 뿔의 그림자가 쪼그려 앉아 새싹 하나를 들여다본다. 뒤에서 덩치 큰 수하가 물뿌리개를 들고 있다. 그녀가 손끝으로 새싹을 건드린다. 새싹이 쑥, 손가락 한 마디만큼 자란다. 덩치 큰 수하가 물뿌리개를 떨어뜨린다. 화면 암전.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png"]},
  {"id":"ep13-a","scene":"EP13 [CUTSCENE 13-A] 심해의 문","full":false,"shot":"돌문이 아주 조금 열렸다가, 스스로 닫힌다. 문틈 너머로 아주 짧게 — 어둠이 아니라 따뜻한 빛이 새어 나온다. 그 빛은 어딘가 슬퍼 보인다.","refs":[]},
  {"id":"ep14-a","scene":"EP14 [CUTSCENE 14-A] 기억과 교과서","full":false,"shot":"화면에 해저에서 본 기억 속 왕의 실루엣과, 학교 교과서 속 '마왕 모르스' 삽화가 겹친다. 기억 속 왕은 아이에게 손을 흔들고 있다. 교과서 속 마왕은 불타는 도시 위에서 포효하고 있다. 같은 왕관. 같은 뿔. 정반대의 얼굴. 독백이 끊긴다. 오웬이 스스로 생각을 멈춘다. 셋이 피식 웃는다. 웃음이 오래가지 않는다.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png","스토리 NPC 일러스트.png"]},
  {"id":"ep15-a","scene":"EP15 [CUTSCENE 15-A] 도서관의 밤","full":false,"shot":"밤의 도서관. 오웬 혼자 공식 역사서 『울토르 왕국사』 원본을 펼친다. 인마대전 장에서 손이 멈춘다. 그 장만 종이 색이 미세하게 다르다. 제본 실을 살펴보면 — 그 몇 장만 나중에 다시 꿰맨 흔적이 있다. 장의 끝, 작은 붉은 도장: 「왕립 기록원 — 교정필」. 오웬이 도장의 날짜를 확인한다. 삼백 년 전. 그는 안경을 벗고, 오래 눈을 감는다. 의심은 '오래전 누군가'를 향한다. 미르엘은 등장하지 않는다.","refs":["미르엘 삼면도.jpg","스토리 NPC 일러스트.png"]},
  {"id":"ep16-a","scene":"EP16 [CUTSCENE 16-A] 지워진 한 글자","full":false,"shot":"오웬이 빛 수정구로 오래된 문서의 지워진 줄을 비춘다. 긁어낸 자국 사이로, 단 한 글자만 살아남아 있다. 「왕」. 그 옆 여백에도 같은 붉은 도장이 찍혀 있다. 「왕립 기록원 — 교정필」.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep17-a","scene":"EP17 [CUTSCENE 17-A] 천공의 빛","full":false,"shot":"밤하늘. 기숙사 옥상에서 일행이 하늘을 올려다본다. 구름이 갈라지며 아주 먼 곳에 거대한 신전의 실루엣이 잠깐 나타났다 사라진다.","refs":[]},
  {"id":"ep18-a","scene":"EP18 [CUTSCENE 18-A] 축제","full":false,"shot":"교정에 작은 여름 축제. 등불, 노점, 하늘로 올라가는 마법 불꽃. 루스벨과 리안이 불꽃 쏘아 올리기 대결을 한다. 둘 다 점점 크게 쏘다가, 마지막 불꽃이 공중에서 부딪쳐 하트 모양이 된다. 주변 학생들이 환호한다. 둘은 동시에 얼굴이 시뻘게진다. 웃음소리 너머, 솜사탕 노점 앞. 미르엘이 솜사탕을 받아 들다가 학생들과 눈이 마주친다.","refs":["미르엘 삼면도.jpg","리안 삼면도.jpg"]},
  {"id":"ep19-a","scene":"EP19 [CUTSCENE 19-A] 자료 보관함","full":false,"shot":"수업이 끝난 뒤. 카엘이 섞여 들어간 3학년 자료를 보관함에 넣고 자물쇠를 채운다. 문서 맨 아래 귀퉁이에 「천공 신전 기록 사본 — 2학년 2학기 열람 예정」이라는 메모가 보인다.","refs":["카엘 삼면도.jpg"]},
]
