// ⚠ 자동 생성 파일 — 손으로 고치지 말 것. 대본 md 를 고친 뒤 `node scripts/build-story-script.mjs 34` 로 다시 만든다.
// EP05~EP34 오프닝(brief)/결말(outro) 대사 + 컷신 슬롯. 원본: 게임 개발 파일/울토르_메인스토리_대사_컷신_*.md (v1.1)
import type { StoryLine } from '@/lib/story'
import type { CutsceneDef } from '@/lib/cutscenes'

export const EP_SCRIPT_GEN: Record<number, { brief: StoryLine[]; outro: StoryLine[] }> = {
  // ═════════ EP05 · 깊은 숲으로 ═════════
  5: {
    brief: [
      {"speaker":"","text":"[방학 첫날] 에르디아 숲 입구. 학교 조사단 캠프가 세워진다. 매미 소리가 시끄럽다.","cut":null},
      {"speaker":"","text":"학생들이 짐을 내리고 텐트를 친다. 리안의 텐트만 세 번째로 무너진다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"방학인데 과제하러 산속까지 온 거 실화냐?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"네가 '학교 밖에서 배우는 게 더 재밌다'고 했잖아."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그건 풍경 좋은 데서 책 읽는다는 뜻이었지. 텐트랑 싸운다는 뜻이 아니라."},
      {"speaker":"도란","portraitId":"comp-doran","text":"말뚝을 반대로 박았어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……말뚝에도 앞뒤가 있어?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"있어."},
      {"speaker":"","text":"오웬이 조사 수첩을 펼친다. 방학인데도 셔츠 단추를 끝까지 잠갔다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이번 조사의 공식 목적은 세 가지입니다. 변이 몬스터의 흔적 확인, 고대 식생 기록 비교, 그리고 지난 학기 발견한 문양의 출처 조사."},
      {"speaker":"주인공","player":true,"text":"교수님은 안 오세요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"미르엘 교수님은 방학 중 교내 결계 정기 점검을 맡고 계십니다. 대신 이걸 주셨습니다."},
      {"speaker":"","text":"오웬이 작은 통신 수정구를 꺼낸다. 수정구 안에 쪽지 하나가 돌돌 말려 있다."},
      {"speaker":"","text":"「무리하지 말 것. 밥은 꼭 챙겨 먹을 것. 리안, 텐트 말뚝은 뾰족한 쪽이 아래란다.」"},
      {"speaker":"리안","portraitId":"comp-rian","text":"……교수님이 어떻게 아셔?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"작년 조사단도 똑같았나 보지."},
      {"speaker":"","text":"짧은 웃음. 그 웃음 위로, 숲 안쪽에서 낮은 울음소리가 들린다. 웃음이 멎는다."},
    ],
    outro: [
      {"speaker":"","text":"[이상한 숲] 셀린이 무릎을 꿇고 잎의 방향을 살핀다.","cut":null},
      {"speaker":"셀린","portraitId":"npc-potion","text":"전부 북쪽을 향해 누워 있어. 지난번 현장수업 때랑 같아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"바람은 남서풍이야. 바람 때문이 아니야."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"그리고… 이 잎, 한여름인데 새순처럼 연해. 숲 전체가 봄을 한 번 더 맞은 것 같아."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그거 좋은 거 아니에요? 숲이 건강하다는 거잖아요."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"사람도 열이 너무 나면 얼굴이 빨개지지. 건강해 보여도, 그건 아픈 거야.","anim":"celine-laugh"},
      {"speaker":"","text":"도란이 흙을 한 줌 들어 보인다. 아래층 흙이 위로 뒤집혀 있다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"밑에서 뭔가 밀고 올라온 흔적이야. 두더지 크기가 아니고."},
      {"speaker":"","text":"주인공이 뿌리 틈에서 작은 검은 결정을 발견한다. 손바닥에 올리자 미지근하다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이거… 지난 학기에 본 거잖아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"온도도 같아. 그때 교수님이 회수하신 거랑 같은 종류야.","anim":"sella-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이번엔 우리가 정식 조사단입니다. 표본으로 보관하고, 학교에 같이 보고하죠."},
      {"speaker":"","text":"야영지의 불이 꺼진 뒤, 카메라가 숲 위로 떠오른다.","cut":"ep05-a"},
      {"speaker":"","text":"뿌리 사이로 금빛 섞인 검은빛이 하나씩 점멸한다. 반딧불이처럼, 그러나 반딧불이보다 느리게."},
      {"speaker":"","text":"빛은 고목숲 가장 깊은 곳으로 흘러간다."},
      {"speaker":"","text":"나무 아래, 지난 학기 뿌리에서 본 것과 같은 원형 문양이 이끼에 반쯤 덮여 있다."},
      {"speaker":"","text":"숲은 잠들지 않았다. 마치 누군가의 꿈을 대신 꾸고 있는 것처럼."},
      {"speaker":"","text":"텐트 하나에서 리안의 잠꼬대가 들린다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……말뚝… 뾰족한 쪽이……"},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP06 · 가시어미 변이체 ═════════
  6: {
    brief: [
      {"speaker":"","text":"[변색된 숲] 숲 한 구역의 나무껍질이 검붉게 물들어 있다. 꽃이 계절을 무시하고 한꺼번에 피어 있다.","cut":null},
      {"speaker":"셀린","portraitId":"npc-potion","text":"이건 병도 아니고 벌레 피해도 아니야."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"마력이 식물 조직 안에 과하게 농축됐어. 넘치도록 부어 놓은 것처럼."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그렇다면 원인이 따로 있다는 뜻이군요. 숲 스스로 이만큼의 마력을 만들 수는 없으니까요."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……새소리가 없어."},
      {"speaker":"","text":"땅이 흔들린다."},
      {"speaker":"","text":"[보스 등장] 거대한 가시어미 변이체가 나무 뒤에서 모습을 드러낸다.","cut":null},
      {"speaker":"","text":"원래 가시어미는 사람 키만 한 덤불형 몬스터다. 눈앞의 것은 집 한 채만 하다."},
      {"speaker":"","text":"몸 곳곳에서 검은 가시가 쉬지 않고 자라나고, 자라자마자 부러지고, 또 자란다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"저게… 가시어미?","anim":"rian-surprise"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"아니. 원래 저 모습이 아니야."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"자라는 걸 멈출 수가 없는 거야. 저건… 고통스러운 거야.","anim":"celine-sad"},
      {"speaker":"도란","portraitId":"comp-doran","text":"진형 잡아!"},
    ],
    outro: [
      {"speaker":"","text":"[변이핵] 변이체가 쓰러진다. 검은 가시들이 땅속으로 파고들며 사라진다.","cut":null},
      {"speaker":"","text":"남은 몸은 시들지 않고, 그 자리에서 작은 꽃밭이 된다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……쓰러뜨렸는데 왜 꽃이 피어?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"이건 죽어서 흩어지는 마력이 아니야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"어딘가로… 흘러가고 있는 것처럼 보이는군요. 땅 밑으로."},
      {"speaker":"","text":"셀린이 꽃밭 한가운데서 주먹만 한 변이핵을 꺼내 봉인 주머니에 넣는다."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"이번에는 내가 직접 챙길게. 학교에 가져가서 제대로 분석해야 해."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……얘도 원래는 그냥 덤불이었겠지.","anim":"doran-think"},
      {"speaker":"","text":"아무도 대답하지 않는다. 리안이 꽃 한 송이를 꺾으려다, 그만두고 손을 거둔다."},
      {"speaker":"","text":"밤. 캠프. 모닥불 앞에서 셀린이 변이핵 분석 메모를 쓰고, 오웬은 통신 수정구로 학교에 보고한다.","cut":"ep06-a"},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"다친 사람은 없니?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"가벼운 찰과상뿐입니다. 리안 학생이 텐트에 걸려 넘어진 것 말고는요."},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"……그건 전투 부상으로 안 쳐 주마. 변이핵은 셀린 선생이 가져오도록 하렴. 학교 연구실에서 같이 보자꾸나."},
      {"speaker":"","text":"통신이 끊긴다. 리안이 모닥불 너머로 소리친다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"다 들렸거든요!"},
      {"speaker":"","text":"셀라가 웃음을 참느라 노트로 얼굴을 가린다. 노트에는 오늘 날짜와 함께 한 줄이 적혀 있다.","anim":"sella-notes"},
      {"speaker":"","text":"「쓰러진 변이체 → 꽃. 마력이 '죽지' 않는다. 어디로 가는가?」"},
    ],
  },
  // ═════════ EP07 · 고목의 문장 ═════════
  7: {
    brief: [
      {"speaker":"","text":"[고목 아래 균열] 변이체의 흔적이 흘러간 방향을 따라가면, 숲에서 가장 오래된 나무 아래 지하 통로가 나타난다.","cut":null},
      {"speaker":"","text":"통로 벽을 따라 뿌리가 혈관처럼 뻗어 있고, 뿌리마다 희미한 금빛이 맥박친다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"이건 자연적으로 생긴 게 아니야. 벽이 너무 반듯해."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"벽면의 문양을 보십시오. 모두 같은 구조입니다. 바깥에서 안쪽으로 감기는 원."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"닫힘… 봉쇄에 가까운 형태야. 뭔가를 '못 나오게' 하는 쪽."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그럼 우리가 지금 못 나오게 한 곳으로 들어가고 있는 거야?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"응."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……'응'이 이렇게 무서운 말이었나."},
      {"speaker":"","text":"[고대목 골렘] 통로 끝, 둥근 방. 벽 한가운데의 거대한 나무 형상이 눈을 뜬다.","cut":null},
      {"speaker":"","text":"이끼가 비처럼 떨어진다. 골렘이 몸을 일으키자 방 전체가 삐걱인다."},
      {"speaker":"고대목 골렘","text":"돌…려…보내라……"},
      {"speaker":"리안","portraitId":"comp-rian","text":"방금 말했지? 나무가 말했지?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"들었어. 네가 두 번 말 안 해도 돼."},
      {"speaker":"도란","portraitId":"comp-doran","text":"말할 여유는 전투 끝나고."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"저 문양… 공격용이 아닙니다. 수호 각인입니다. 저건 '지키는' 존재예요!"},
      {"speaker":"리안","portraitId":"comp-rian","text":"지키는 애가 왜 우릴 때리려 하는데요!"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"우리가 '지켜야 할 쪽'에 서 있으니까겠죠!"},
    ],
    outro: [
      {"speaker":"","text":"[마지막 문장] 골렘이 무너진다. 무릎을 꿇은 채, 마지막 힘으로 돌판 하나를 내민다.","cut":null},
      {"speaker":"","text":"돌판에는 네 개의 원과, 그 원들을 가로지르는 닫힌 문이 새겨져 있다."},
      {"speaker":"주인공","player":true,"text":"네 개의 원… 뭘 뜻하는 거지?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"아직은 알 수 없습니다. 다만 네 개 중 하나만 테두리가 금으로 덧칠되어 있군요."},
      {"speaker":"","text":"골렘의 마지막 음성. 아까보다 훨씬 작고, 거의 부탁처럼 들린다."},
      {"speaker":"고대목 골렘","text":"문을… 닫아라… 기쁨이… 새어 나간다……"},
      {"speaker":"","text":"골렘의 눈빛이 꺼진다. 방 안의 금빛 맥박이 아주 조금 약해진다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……기쁨?","anim":"sella-think"},
      {"speaker":"","text":"모닥불. 세 동료가 이번 원정을 돌아본다. 불티가 별 사이로 올라간다.","cut":"ep07-a"},
      {"speaker":"리안","portraitId":"comp-rian","text":"그래도 재밌었다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"보스가 재밌었던 거겠지."},
      {"speaker":"도란","portraitId":"comp-doran","text":"다음엔 덜 위험했으면 좋겠고."},
      {"speaker":"리안","portraitId":"comp-rian","text":"근데 그 골렘… 우리 미워해서 싸운 거 아니지?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"응. 일해서 싸운 거야."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……일하다가 쓰러진 거네."},
      {"speaker":"","text":"모닥불이 탁 튄다. 아무도 한동안 말이 없다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"'기쁨이 새어 나간다.' 무섭다는 말이 아니라 기쁘다는 말인데, 왜 이렇게 무섭지.","anim":"sella-think"},
      {"speaker":"","text":"얼굴과 이름은 보여 주지 않는다.","cut":"ep07-b"},
      {"speaker":"","text":"용암 온천. 김이 자욱하다. 거대한 뿔의 그림자가 어깨까지 몸을 담그고 있다."},
      {"speaker":"","text":"옆에서 작은 날개 달린 수하가 장기판을 들고 종종걸음으로 온다."},
      {"speaker":"작은 수하","text":"폐하! 그롯 님이 또 장기에서 이기셨다고 자랑하고 다니십니다!"},
      {"speaker":"뿔의 그림자","text":"그 녀석은 말이 안 되는 곳으로 말을 옮긴단다."},
      {"speaker":"작은 수하","text":"그럼 왜 그냥 두십니까?"},
      {"speaker":"뿔의 그림자","text":"이기면 저렇게 좋아하니까."},
      {"speaker":"","text":"온천 바닥의 바위틈이 은은한 금빛으로 물든다."},
      {"speaker":"","text":"같은 순간 — 아주 먼 남쪽, 무너진 골렘의 방에서 꺼졌던 금빛 맥박이 다시 한 번, 약하게 뛴다."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP08 · 숲을 떠나 바다로 ═════════
  8: {
    brief: [
      {"speaker":"","text":"[개강] 강의실. 방학 동안 햇볕에 그을린 학생들. 루스벨만 유독 피부가 멀쩡하다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"너 방학 때 뭐 했어? 하나도 안 탔네."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"화염 특강. 불 옆에 있으면 오히려 안 타."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……그게 말이 돼?"},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"나한텐 돼."},
      {"speaker":"","text":"미르엘이 들어온다. 교탁에 조사단 보고서 다발을 내려놓는다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"방학 동안 수고했다. 조사단 보고서는 전부 읽었단다. 특히 '발견자 리안'이라고 쓴 부분이 아주 크더구나."},
      {"speaker":"","text":"교실에 웃음이 번진다. 리안이 뿌듯하게 가슴을 편다."},
      {"speaker":"","text":"수업 후, 주인공이 돌판의 탁본을 들고 교탁으로 간다."},
      {"speaker":"주인공","player":true,"text":"교수님, 이 문양을 아세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"오래된 봉인술과 닮았구나. 수호 각인 쪽 계열이야.","anim":"mirel-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"'닮았다'고 하시는 건, 확실하지 않다는 뜻입니까?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"기록이 부족하니까. 모르는 걸 아는 척하는 게 학자에게 제일 위험한 일이란다, 오웬."},
      {"speaker":"","text":"오웬이 고개를 끄덕인다. 존경이 섞인 끄덕임이다.","anim":"owen-think"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"이건 네가 계속 가지고 있으렴. 발견한 사람이 끝까지 보는 게 맞지."},
    ],
    outro: [
      {"speaker":"","text":"[해안 현장실습] 셀린이 다음 현장실습을 소개한다. 칠판에 물고기 그림이 그려져 있다. 생각보다 못 그렸다.","cut":null},
      {"speaker":"셀린","portraitId":"npc-potion","text":"이번 현장수업은 에르디아 해안이야. 해양 생태 조사랑 낚시 실습."},
      {"speaker":"리안","portraitId":"comp-rian","text":"바다!"},
      {"speaker":"셀린","portraitId":"npc-potion","text":"칠판 그림은 고등어야."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……저는 그걸 고양이로 봤어요."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"…다음엔 반 선생님한테 그려 달라고 할게."},
      {"speaker":"도란","portraitId":"comp-doran","text":"이번에도 보스 있는 건 아니겠지?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그런 말 하면 꼭 있어."},
      {"speaker":"","text":"반이 방수 가방을 하나씩 내민다.","anim":"van-give"},
      {"speaker":"반","portraitId":"npc-weapon","text":"장비부터 챙겨. 물은 적보다 장비를 더 자주 망가뜨린다."},
      {"speaker":"반","portraitId":"npc-weapon","text":"부서지면—"},
      {"speaker":"리안 · 셀라 · 도란","text":"돌아와서 말할게요."},
      {"speaker":"반","portraitId":"npc-weapon","text":"……그래."},
      {"speaker":"","text":"숲을 빠져나와 언덕을 넘는 주인공 시점. 숲의 녹음이 뒤로 물러나고, 화면이 한꺼번에 넓어진다.","cut":"ep08-a"},
      {"speaker":"","text":"끝없는 푸른 바다. 소금 냄새가 화면 너머로 느껴질 것처럼 바람이 분다."},
      {"speaker":"","text":"리안이 언덕 위에서 두 팔을 벌린다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"바다다아아—!"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"소리 지르면 바다가 대답해 줘?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"안 해 줘도 질러야 하는 거야, 이건."},
      {"speaker":"","text":"짧은 순간, 물결 위에 고목에서 본 원형 문양이 비친다. 아무도 보지 못한다."},
    ],
  },
  // ═════════ EP09 · 바다는 기다리는 사람에게 ═════════
  9: {
    brief: [
      {"speaker":"","text":"[어민의 부탁] 작은 선착장. 늙은 어부 토마가 텅 빈 그물을 손질하고 있다.","cut":null},
      {"speaker":"토마","text":"요즘 물고기가 깊은 곳으로만 가. 사십 년 바다에 나갔는데 이런 해는 처음이야."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"수온 변화인가요?"},
      {"speaker":"토마","text":"그랬으면 좋겠는데… 밤마다 바다 밑에서 빛이 올라와. 고기들이 그 빛 쪽으로 몰려가."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그런 얘기 들으면 더 가 보고 싶은데.","anim":"rian-laugh"},
      {"speaker":"도란","portraitId":"comp-doran","text":"그래서 네가 위험한 거야."},
      {"speaker":"토마","text":"자네 같은 젊은이를 바다가 제일 좋아하지. 데려가고 싶어서."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……농담이시죠?"},
      {"speaker":"토마","text":"반은."},
    ],
    outro: [
      {"speaker":"","text":"[폐등대] 해질 무렵, 바위곶 끝의 폐등대. 녹슨 계단이 바람에 울린다.","cut":null},
      {"speaker":"","text":"꼭대기 등실 바닥에 원형 문양이 새겨져 있다. 소금기에 반쯤 지워졌다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"여기… 숲에서 본 거랑 비슷해."},
      {"speaker":"","text":"오웬이 문양을 종이에 베낀다. 손이 빠르고 정확하다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"형태는 같지만 중심부가 다릅니다. 숲의 것은 '안으로 감기는' 원이었는데, 이건 '바깥으로 닫히는' 원입니다."},
      {"speaker":"주인공","player":true,"text":"같은 사람이 만든 걸까요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"같은 시대의 기술인 것은 분명합니다. 그 이상은… 아직 모르는 게 너무 많습니다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"근데 이 등대, 왜 버려진 거예요?"},
      {"speaker":"토마","text":"불을 켜도, 바다 밑 빛이 더 밝아서. 배들이 자꾸 그쪽으로 갔거든."},
      {"speaker":"","text":"밤. 해안 마을의 집들이 하나둘 창문을 닫는다. 덧문 닫히는 소리가 파도 소리를 따라 번진다.","cut":"ep09-a"},
      {"speaker":"","text":"수평선 아래에서 푸른빛이 솟는다. 한 번. 두 번. 세 번."},
      {"speaker":"","text":"빛이 솟을 때마다 바다 전체가 숨을 들이쉬는 것처럼 조용해진다."},
      {"speaker":"토마","text":"저건… 다시 시작됐군. 내 할아버지 때 이후 처음이야."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"숲이 이상해진 것도 이번 봄부터. 바다도 이번 해부터.","anim":"sella-think"},
      {"speaker":"도란","portraitId":"comp-doran","text":"같이 시작됐다는 거네."},
      {"speaker":"","text":"카메라가 물속으로 내려간다. 빛을 따라 아래로, 더 아래로."},
      {"speaker":"","text":"해저 깊은 곳에 거대한 돌문이 짧게 보인다. 문 표면의 원형 홈 하나가 빛에 맞춰 떨리고 있다."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP10 · 중간고사, 그리고 해저 유적 ═════════
  10: {
    brief: [
      {"speaker":"","text":"[중간고사] 오웬이 감독관으로 들어와 시험지를 나눠 준다. 교실에 종이 넘기는 소리만 가득하다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이번 시험은 단순 암기만으로 풀 수 없습니다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그 말은 어렵다는 뜻이네요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"정확합니다. 첫 문제부터 맞히셨군요."},
      {"speaker":"","text":"실패해도 스토리는 진행되며 보정 과제가 열린다."},
      {"speaker":"","text":"시험 후 복도. 결과 게시판 앞."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"화염 실기 1등. 또."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……난 역사에서 1등 했거든."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"네가? 역사를?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"찍었는데 다 맞았어."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그건 1등이 아니라 사고야."},
      {"speaker":"","text":"[얕은 해저 조사] 해안 실습. 수중 호흡 물약을 마시고 얕은 바다로 들어간다.","cut":null},
      {"speaker":"","text":"물속은 조용하다. 햇빛이 물결 무늬로 모래 위에 흔들린다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"잠깐. 저 돌은 자연석이 아니야."},
      {"speaker":"","text":"주인공이 조사하면, 모래 밑에서 반듯한 석재와 계단 일부가 드러난다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"문이 있었던 흔적 같아. 계단이 아래로 이어져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"바다 밑에 건물이 있었다고? 누가 바다 밑에 집을 지어?"},
      {"speaker":"셀린","portraitId":"npc-potion","text":"처음부터 바다 밑은 아니었을 거야. 땅이었던 곳이 가라앉은 거지."},
    ],
    outro: [
      {"speaker":"","text":"[오웬의 판독] 선착장으로 돌아와 젖은 탁본을 말린다. 오웬이 기호 하나하나를 손가락으로 짚어 간다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"울토르에서 쓰는 문자보다 오래됐습니다. 지금 왕국 문자의 조상보다도 오래됐을 겁니다."},
      {"speaker":"주인공","player":true,"text":"읽을 수 있어요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"지금은 아닙니다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"부끄러운 고백이지만, 사서 생활 이십 년 만에 '못 읽겠다'는 말을 이렇게 자주 하게 된 건 처음입니다."},
      {"speaker":"","text":"이 '못 읽는 문자'는 훗날 설원의 석비와 연결한다."},
      {"speaker":"","text":"해저 계단 끝. 주인공이 돌문 표면에 손을 대자, 네 개의 원형 홈이 잠깐 빛난다.","cut":"ep10-a"},
      {"speaker":"","text":"그중 하나 — 숲의 돌판에서 금으로 덧칠되어 있던 바로 그 자리 — 가 가장 밝다."},
      {"speaker":"","text":"물결이 거꾸로 흐르는 것처럼 보이고, 문이 아주 미세하게 떨린다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"뭔가… 아직 살아 있어."},
      {"speaker":"","text":"문은 열리지 않는다. 떨림이 천천히 가라앉는다."},
    ],
  },
  // ═════════ EP11 · 파도 아래 잠든 것 ═════════
  11: {
    brief: [
      {"speaker":"","text":"[학기말] 방파제 위. 학기말 시험이 끝나고, 일행이 다리를 바다 쪽으로 늘어뜨리고 앉아 있다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"한 학기 진짜 길었다. 그래도 많이 배웠네."},
      {"speaker":"주인공","player":true,"text":"근데 유적 문제는 아직 아무것도 모르겠어요."},
      {"speaker":"도란","portraitId":"comp-doran","text":"숲도 모르고, 바다도 모르고."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그래서 이번엔 더 아래로 가는 거야. 계단이 끝나는 곳까지.","anim":"sella-think"},
      {"speaker":"셀린","portraitId":"npc-potion","text":"그 전에 이것부터. 수중 호흡 물약 두 배 농도. 맛은… 각오하렴."},
      {"speaker":"","text":"리안이 한 모금 마시고 얼굴을 구긴다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……바다 맛이에요."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"바다 들어가는데 바다 맛이면 딱 좋지."},
      {"speaker":"","text":"[해안 수호수] 해저 계단 아래, 유적 입구. 산호로 뒤덮인 거대한 거북 형상의 수호수가 입구를 막고 있다.","cut":null},
      {"speaker":"","text":"수호수는 일행을 보자 공격하지 않고, 천천히 몸을 돌려 입구를 더 단단히 가린다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이건 우리 못 들어가게 막는 거지?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"아마 지키는 거겠지. 숲의 골렘처럼."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"죽이지 말고 제압하자. 저 애도 일하는 중이야."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……요즘 우리가 싸우는 애들 다 일하는 중이네."},
    ],
    outro: [
      {"speaker":"","text":"[첫 파편] 수호수가 천천히 물러나 유적 깊은 어둠 속으로 사라진다.","cut":null},
      {"speaker":"","text":"자리에 남은 것은 손바닥만 한 인장 파편 하나. 표면에 원의 일부가 새겨져 있다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"숲에서 본 것과 같은 계열이야. 온도도 같아. 따뜻해."},
      {"speaker":"도란","portraitId":"comp-doran","text":"그럼 서로 다른 곳에서 같은 일이 생기고 있다는 거네."},
      {"speaker":"리안","portraitId":"comp-rian","text":"숲이랑 바다가 무슨 상관인데?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그걸 모르니까 무서운 거야."},
      {"speaker":"","text":"화면이 둘로 갈라진다. 왼쪽은 에르디아 숲 깊은 곳의 원형 문양, 오른쪽은 해저 돌문의 원형 홈.","cut":"ep11-a"},
      {"speaker":"","text":"둘이 동시에 빛난다. 빛줄기가 서로를 향해 뻗어 — 연결되려는 순간, 끊어진다."},
      {"speaker":"","text":"그리고 아주 잠깐, 두 빛줄기가 같은 방향을 가리킨다. 북쪽."},
      {"speaker":"","text":"멀리 떨어진 두 장소에서, 같은 무언가가 같은 쪽을 바라보고 있었다."},
    ],
  },
  // ═════════ EP12 · 겨울 바다의 불빛 ═════════
  12: {
    brief: [
      {"speaker":"","text":"[아틀란티스 도착] 물 위에 걸쳐 지어진 하얀 도시. 수로마다 작은 배가 오가고, 다리 위에서 상인들이 생선을 외친다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"와… 진짜 도시가 물 위에 떠 있네.","anim":"rian-surprise"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"떠 있는 건 아니고, 수로와 건축이 함께 설계된 도시입니다. 지반 아래로 기둥이 삼천 개쯤 박혀 있죠."},
      {"speaker":"리안","portraitId":"comp-rian","text":"사서님은 감동을 숫자로 하세요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"숫자를 알면 감동이 두 배가 됩니다. 삼천 개입니다, 리안 학생. 삼천 개."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……두 배 됐어.","anim":"doran-think"},
      {"speaker":"","text":"[방학 생활] 낚시, 해양 채집, 상인 심부름, 주민 도움 퀘스트.","cut":null},
      {"speaker":"","text":"선술집 주인이 일행에게 생선 수프를 공짜로 내준다. 지난 학기 해안 마을에서 토마를 도운 소문이 여기까지 퍼졌다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"이번 방학은 좀 여유롭네."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그렇게 말하면 꼭 일이 생겨."},
      {"speaker":"리안","portraitId":"comp-rian","text":"넌 맨날 그 말 하더라."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그리고 맨날 맞지."},
      {"speaker":"","text":"[밤의 불빛] 밤. 선착장. 밤바다에서 거대한 푸른빛이 솟는다. 지난번 해안에서 본 것보다 훨씬 크다.","cut":null},
      {"speaker":"","text":"도시 사람들이 일제히 등불을 끄고 고개를 돌린다."},
      {"speaker":"주민","text":"저 빛은 보지 않는 게 좋아."},
      {"speaker":"주인공","player":true,"text":"왜요?"},
      {"speaker":"주민","text":"오래전부터 저 빛이 나타난 해엔 꼭 사고가 났거든. 어른들은 '바다 밑 재앙이 뒤척인다'고 했어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"재앙이 뒤척여요? 자다가?","anim":"rian-think"},
      {"speaker":"주민","text":"그래. 그러니까 깨우지 말라고."},
    ],
    outro: [
      {"speaker":"","text":"카메라가 수면 아래로 내려간다. 거대한 광원이 해저 깊은 곳에서 맥박친다.","cut":"ep12-a"},
      {"speaker":"","text":"그 아래, 반쯤 모래에 잠긴 돌문. 문의 네 홈 중 하나가 광원과 같은 박자로 깜빡인다."},
      {"speaker":"","text":"용암이 흐르는 마을 외곽의 작은 밭. 화산재 흙에 무언가가 줄지어 심겨 있다.","cut":"ep12-b"},
      {"speaker":"","text":"거대한 뿔의 그림자가 쪼그려 앉아 새싹 하나를 들여다본다. 뒤에서 덩치 큰 수하가 물뿌리개를 들고 있다."},
      {"speaker":"덩치 큰 수하","text":"폐하, 그건 잡초입니다."},
      {"speaker":"뿔의 그림자","text":"알고 있다."},
      {"speaker":"덩치 큰 수하","text":"……그럼 왜 물을 주라고 하십니까?"},
      {"speaker":"뿔의 그림자","text":"여기까지 와서 자란 게 기특하지 않느냐."},
      {"speaker":"","text":"그녀가 손끝으로 새싹을 건드린다. 새싹이 쑥, 손가락 한 마디만큼 자란다."},
      {"speaker":"","text":"덩치 큰 수하가 물뿌리개를 떨어뜨린다."},
      {"speaker":"덩치 큰 수하","text":"폐하. 방금……"},
      {"speaker":"뿔의 그림자","text":"……그러게. 방금."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP13 · 해파리 여왕 ═════════
  13: {
    brief: [
      {"speaker":"","text":"[심해 진입] 빛이 닿지 않는 깊이. 일행의 수정구 불빛만이 주변을 비춘다.","cut":null},
      {"speaker":"","text":"가끔 거대한 무언가가 불빛 바깥을 스쳐 지나간다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"돌아갈 길은 반드시 표시해 두십시오. 반드시."},
      {"speaker":"리안","portraitId":"comp-rian","text":"사서님 무서우세요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"저는 지금 매우 침착합니다. 단지 이 깊이에서 길을 잃으면 도서관 반납 기한을 영영 못 지킬 뿐입니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……무서우신 거네."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이번엔 진짜 아래로 간다."},
      {"speaker":"","text":"[해파리 여왕] 거대한 반투명 해파리가 어둠 속에서 피어오른다. 몸 안에서 수천 개의 작은 빛이 별처럼 흐른다.","cut":null},
      {"speaker":"","text":"주변의 작은 해파리들이 여왕을 향해 빛을 흘려보낸다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……예쁘다.","anim":"doran-think"},
      {"speaker":"리안","portraitId":"comp-rian","text":"지금 그 말 할 때야?!"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"저 움직임… 마력진이랑 같아. 여왕 혼자가 아니라, 주변 전체가 하나의 진을 그리고 있어."},
      {"speaker":"","text":"여왕의 촉수가 휘둘러질 때마다 빛의 궤적이 하나의 문양을 그려 간다. 해저 돌문의 원형 홈과 같은 모양이다."},
    ],
    outro: [
      {"speaker":"","text":"[전투 후] 여왕이 빛을 잃고 천천히 가라앉는다. 작은 해파리들이 흩어진다.","cut":null},
      {"speaker":"","text":"여왕이 그리던 문양이 미완성인 채로 물속에 남아 서서히 흐려진다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이건 생태 이상이 아닙니다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"여왕은 문을 '열려고' 한 게 아닙니다. 문이 먼저 흔들렸고, 여왕은 그걸 다시 잠그려고 진을 그리고 있었던 겁니다."},
      {"speaker":"주인공","player":true,"text":"그럼 문을 흔드는 건 누군데요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……문 안쪽, 혹은 문 너머 어딘가. 무언가가 깨어나고 있습니다.","anim":"owen-think"},
      {"speaker":"","text":"돌문이 아주 조금 열렸다가, 스스로 닫힌다.","cut":"ep13-a"},
      {"speaker":"","text":"문틈 너머로 아주 짧게 — 어둠이 아니라 따뜻한 빛이 새어 나온다. 그 빛은 어딘가 슬퍼 보인다."},
    ],
  },
  // ═════════ EP14 · 암초왕의 기억 ═════════
  14: {
    brief: [
      {"speaker":"","text":"[암초왕의 영역] 심해 유적의 중심. 산호와 바위가 엉겨 붙은 왕좌 위에 거대한 암초의 거인이 앉아 있다.","cut":null},
      {"speaker":"","text":"거인은 일어나지 않는다. 다만 눈을 뜬다."},
      {"speaker":"암초왕","text":"인간은 또 문을 찾아왔군."},
      {"speaker":"리안","portraitId":"comp-rian","text":"또 말한다!","anim":"rian-surprise"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"요즘 말하는 애들 많아. 적응해."},
      {"speaker":"주인공","player":true,"text":"우리는 이 문이 뭔지 알고 싶을 뿐이에요."},
      {"speaker":"암초왕","text":"알면, 부르게 된다. 부르면, 또 빼앗으러 온다."},
      {"speaker":"암초왕","text":"그 이름을 부르지 마라. 이번에는 내가 지킨다."},
    ],
    outro: [
      {"speaker":"","text":"[보스전] 암초왕이 일어선다. 그러나 공격은 대부분 일행을 문에서 '떼어 놓는' 동작이다.","cut":null},
      {"speaker":"","text":"HP가 줄어들수록 암초왕은 공격하기보다 등 뒤의 문을 몸으로 가린다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……이 사람, 우리 죽이려는 게 아니야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"알고 있습니다. 알고 있어서 더 괴롭군요."},
      {"speaker":"","text":"[기억의 파편] 암초왕이 무너지며 몸에서 빛의 파편이 흩어진다. 파편 하나가 주인공에게 닿는 순간, 시야가 바뀐다.","cut":null},
      {"speaker":"","text":"— 오래전의 바닷가 도시. 지금의 아틀란티스와 닮았지만 훨씬 오래된."},
      {"speaker":"","text":"인간과, 뿔이 달린 이들과, 비늘이 있는 이들이 같은 시장에서 생선을 고른다."},
      {"speaker":"","text":"높은 계단 위에서 왕관을 쓴 누군가가 그 시장을 내려다본다. 얼굴은 빛에 가려 보이지 않는다."},
      {"speaker":"","text":"그녀가 웃는다. 아이 하나가 손을 흔들고, 그녀도 손을 흔들어 준다."},
      {"speaker":"","text":"장면이 일그러진다. 같은 계단 위, 사슬. 의식. 네 개의 빛이 한 사람의 몸에서 뜯겨 나간다."},
      {"speaker":"","text":"비명은 들리지 않는다. 다만 바다가 한꺼번에 차가워진다."},
      {"speaker":"","text":"시야가 돌아온다. 주인공의 손이 떨리고 있다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"야, 괜찮아? 너 지금 울어."},
      {"speaker":"주인공","player":true,"text":"……어. 왜 그러지."},
      {"speaker":"","text":"[이름] 문 옆 벽면. 고대문자 위로, 날카로운 정으로 덧새긴 다른 글자들이 겹쳐 있다.","cut":null},
      {"speaker":"","text":"오웬이 손전등을 비추다가 멈춘다. 덧새긴 쪽은 — 읽을 수 있다. 오래된 왕국 공용문자다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"마왕… 모… 르… 스."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"'재앙의 왕 모르스, 이곳에 봉하다.'"},
      {"speaker":"주인공","player":true,"text":"모르스?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"교과서에만 나오던 이름을, 이런 곳에서 직접 확인하는 건 처음입니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"근데 이상해. 아래 글자는 고대문자고, 위 글자는 우리 문자의 옛날 형태잖아.","anim":"sella-think"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그럼 이 이름은… 원래 여기 쓰여 있던 게 아니라, 누가 나중에 와서 위에 덧쓴 거야."},
      {"speaker":"","text":"정적. 물방울 떨어지는 소리."},
      {"speaker":"도란","portraitId":"comp-doran","text":"아래에는 뭐라고 쓰여 있었는데?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……읽을 수 없습니다. 아무도."},
      {"speaker":"","text":"화면에 해저에서 본 기억 속 왕의 실루엣과, 학교 교과서 속 '마왕 모르스' 삽화가 겹친다.","cut":"ep14-a"},
      {"speaker":"","text":"기억 속 왕은 아이에게 손을 흔들고 있다. 교과서 속 마왕은 불타는 도시 위에서 포효하고 있다."},
      {"speaker":"","text":"같은 왕관. 같은 뿔. 정반대의 얼굴."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"같은 인물인데… 왜 이렇게 다르지."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"기억이 틀린 걸까. 아니면 교과서가—"},
      {"speaker":"","text":"독백이 끊긴다. 오웬이 스스로 생각을 멈춘다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"근데 아까 그 기억에서… 시장 생선 엄청 싱싱해 보이지 않았어?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"……봤어."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"너희 둘은 진짜."},
      {"speaker":"","text":"셋이 피식 웃는다. 웃음이 오래가지 않는다."},
    ],
  },
  // ═════════ EP15 · 돌아온 학생, 남겨진 질문 ═════════
  15: {
    brief: [
      {"speaker":"","text":"[개강] 본관 계단. 유나가 2학년 배지를 단 후배들을 맞는다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"2학년부터는 수업이 좀 더 전문적으로 변할 거야.","anim":"yuna-think"},
      {"speaker":"리안","portraitId":"comp-rian","text":"1학년도 충분히 힘들었는데요."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"그래서 2학년이지. 힘든 걸 버틴 사람한테 더 힘든 걸 주는 게 학교거든."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……그거 학교 홍보 문구로 쓰면 안 되겠다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"난 2학년 수업 미리 다 봤어. 별거 없더라."},
      {"speaker":"리안","portraitId":"comp-rian","text":"저 말 1학년 때도 했다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"1학년 때도 맞았지."},
    ],
    outro: [
      {"speaker":"","text":"[모르스의 이름] 역사 수업. 미르엘의 강의. 오웬이 해안에서 베껴 온 기록을 들고 청강하러 들어와 있다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"인마대전. 오백 년 전, 마왕 모르스가 인간 왕국을 침공하며 시작된 전쟁이지."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"교수님. 해안 심해 유적에서 그 이름을 직접 확인했습니다. 다만 그 이름은 원래 문장 위에 덧새겨져 있었습니다."},
      {"speaker":"","text":"교실이 조용해진다."},
      {"speaker":"주인공","player":true,"text":"그리고… 거기서 본 기억 속의 왕은, 교과서랑 달랐어요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"역사는 보는 사람에 따라 조금씩 다르게 보이는 법이지."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"하지만 날짜까지 달라집니다. 해안의 기록과 공식 연대표가 삼 년이나 어긋납니다."},
      {"speaker":"","text":"정적. 학생들이 미르엘의 눈치를 본다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"좋다. 그럼 숙제로 하자꾸나.","anim":"mirel-laugh"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"두 기록이 다르면, 어느 쪽이 먼저 쓰였는지부터 확인하렴. 누가, 언제, 왜 썼는지. 그게 역사학의 첫걸음이란다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……질문했더니 숙제가 생겼어."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"오웬 사서님 탓이야."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"역사학의 첫걸음입니다."},
      {"speaker":"","text":"밤의 도서관. 오웬 혼자 공식 역사서 『울토르 왕국사』 원본을 펼친다.","cut":"ep15-a"},
      {"speaker":"","text":"인마대전 장에서 손이 멈춘다. 그 장만 종이 색이 미세하게 다르다."},
      {"speaker":"","text":"제본 실을 살펴보면 — 그 몇 장만 나중에 다시 꿰맨 흔적이 있다."},
      {"speaker":"","text":"장의 끝, 작은 붉은 도장: 「왕립 기록원 — 교정필」."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"교정… 무엇을 바로잡았다는 거지."},
      {"speaker":"","text":"오웬이 도장의 날짜를 확인한다. 삼백 년 전.","anim":"owen-think"},
      {"speaker":"","text":"그는 안경을 벗고, 오래 눈을 감는다."},
      {"speaker":"","text":"……이건 학생들에게 아직 보여 주지 말자."},
      {"speaker":"","text":"의심은 '오래전 누군가'를 향한다. 미르엘은 등장하지 않는다."},
    ],
  },
  // ═════════ EP16 · 기록이 다르게 쓰여 있다 ═════════
  16: {
    brief: [
      {"speaker":"","text":"[문헌 대조] 도서관 열람실. 오웬이 두 판본을 책상에 나란히 펼친다. 셀라가 숙제를 핑계로 와 있다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"같은 사건인데 날짜가 세 군데서 다릅니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"필사 오류?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"한 번이면 그렇겠죠."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그런데 세 번 다, 모르스에게 불리한 쪽으로 틀렸습니다. 오류는 보통 그렇게 한쪽으로만 나지 않습니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……누가 일부러 고쳤다는 거네요.","anim":"sella-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그렇게 말하기엔 아직 증거가 부족합니다. 하지만 그렇게 생각하지 않기엔 우연이 너무 많군요."},
    ],
    outro: [
      {"speaker":"","text":"[카엘의 지도] 빙결 실습실. 조교 카엘이 학생들의 보고서를 쌓아 두고 낡은 지도 한 장을 꺼낸다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"이거. 스톰헤이븐 쪽 지도."},
      {"speaker":"주인공","player":true,"text":"교과서에 없는 길이 있네요?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"있어. 내 고향이 거기 아래 마을이야. 어릴 때 할머니가 '하늘로 가는 옛길'이라고 불렀지."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"근데 왜 공식 지도엔 없어요?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"그래서 확인하려는 거다. …보고서는 다들 냈지?"},
      {"speaker":"주인공","player":true,"text":"……내일까지는요."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"오늘까지야."},
      {"speaker":"","text":"[미르엘과의 대화] 복도. 미르엘이 주인공과 셀라를 불러 세운다. 손에 두 사람의 숙제가 들려 있다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"숙제 잘 봤다. 셀라, 날짜 대조표는 교수들보다 낫더구나."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……감사합니다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"다만, 카엘 조교가 스톰헤이븐 옛길 이야기를 했다지?"},
      {"speaker":"주인공","player":true,"text":"네. 직접 가 보고 싶어요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"학생이 혼자 너무 깊이 들어갈 길은 아니란다. 그 길은 바람이 사람을 날려 보내는 곳이야."},
      {"speaker":"주인공","player":true,"text":"그럼 교수님은 반대세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"반대가 아니라 걱정이지. 정식으로 가는 방법을 찾아보자꾸나. 그건 내가 도와줄 수 있으니.","anim":"mirel-laugh"},
      {"speaker":"","text":"그녀는 걱정하는 교수처럼 보인다. 그리고 실제로, 다음 막에서 길을 열어 준다."},
      {"speaker":"","text":"오웬이 빛 수정구로 오래된 문서의 지워진 줄을 비춘다.","anim":"owen-think","cut":"ep16-a"},
      {"speaker":"","text":"긁어낸 자국 사이로, 단 한 글자만 살아남아 있다. 「왕」."},
      {"speaker":"","text":"그 옆 여백에도 같은 붉은 도장이 찍혀 있다. 「왕립 기록원 — 교정필」."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"마왕이 아니라… 왕."},
    ],
  },
  // ═════════ EP17 · 하늘에서 내려온 초대 ═════════
  17: {
    brief: [
      {"speaker":"","text":"[기말시험] 종합 실기: 영창 암기 → 리듬 타이밍 → 원소 실전.","cut":null},
      {"speaker":"","text":"시험 직전, 대기실. 리안이 손바닥에 영창을 적다가 도란에게 들킨다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"그거 땀 나면 번져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……'불꽃이여, 나의 ㅁ…ㄴ…'"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"시험은 너를 평가하는 자리가 아니라, 다음에 무엇을 배워야 하는지 알려 주는 자리란다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"리안은 다음에 손 씻는 법부터 배우면 되겠구나."},
    ],
    outro: [
      {"speaker":"","text":"[초대장] 시험이 끝난 뒤. 카엘이 은빛 봉랍으로 봉인된 편지를 들고 온다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"스톰헤이븐 연구진이 정식으로 초청했어. 천공 신전 자료 열람 허가."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"천공 신전 기록 보관소군요. 이건 왕국 학자들도 평생 한 번 들어가기 힘든 곳입니다.","anim":"owen-surprise"},
      {"speaker":"리안","portraitId":"comp-rian","text":"그런 데를 우리가 어떻게?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"교장 선생님이 추천서를 써 주셨다. 직접."},
      {"speaker":"","text":"일행이 서로를 본다. 지난번 \"도와줄 수 있으니\"라던 말이 떠오른다."},
      {"speaker":"","text":"[승인] 교장실. 미르엘이 원정 계획서에 서명한다. 망설임이 없다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"좋아. 다녀오렴."},
      {"speaker":"주인공","player":true,"text":"교수님도 같이 가세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"나는 학교를 지켜야지. 교장이 방학마다 자리를 비우면 학교가 무너진단다. …농담이 아니라, 진짜로 결계가 무너져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……진짜요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"반쯤은.","anim":"mirel-laugh"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"대신 결과는 꼭 내게 보고하렴. 너희가 찾은 걸 제일 먼저 듣고 싶구나."},
      {"speaker":"","text":"다정하고, 기대에 찬 목소리다."},
      {"speaker":"","text":"밤하늘. 기숙사 옥상에서 일행이 하늘을 올려다본다.","cut":"ep17-a"},
      {"speaker":"","text":"구름이 갈라지며 아주 먼 곳에 거대한 신전의 실루엣이 잠깐 나타났다 사라진다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……저기까지 걸어가는 거야?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"반은 걸어서, 반은 날아서. 멀미약 챙겨."},
      {"speaker":"","text":"바다 아래에서 찾은 문은, 하늘 위로 이어져 있었다."},
    ],
  },
  // ═════════ EP18 · 방학은 조금 천천히 ═════════
  18: {
    brief: [
      {"speaker":"","text":"[동아리] 학교 게시판. 여름 동아리 모집 공고가 빽빽하다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"이번 여름은 네가 하고 싶은 걸 해 봐."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"2학년부터는 다들 진로가 조금씩 보이기 시작하거든. 그 전에 좋아하는 걸 하나쯤 찾아 둬."},
      {"speaker":"리안","portraitId":"comp-rian","text":"'용암 요리 동아리'? 이거다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그거 작년에 실습실 태워서 폐부됐어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그럼 왜 아직 붙어 있어?"},
      {"speaker":"유나","portraitId":"comp-yuna","text":"……부장이 졸업을 안 했거든."},
    ],
    outro: [
      {"speaker":"","text":"[개인공간] 주인공의 기숙사 방을 꾸민다. 동료들이 각자 가구를 들고 들이닥친다.","cut":null},
      {"speaker":"리안","portraitId":"comp-rian","text":"이거 놓자. 멋있잖아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"공간 낭비야. 그리고 그거 눈이 따라와."},
      {"speaker":"도란","portraitId":"comp-doran","text":"그래도 이건 하나쯤 있으면 좋겠는데."},
      {"speaker":"리안","portraitId":"comp-rian","text":"왜 도란 거만 바로 통과야?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"눈이 안 따라오니까."},
      {"speaker":"","text":"생활 콘텐츠 비중을 높인다(하우징·요리·낚시·제작)."},
      {"speaker":"","text":"[여름 산책] 해 질 녘 호숫가. 유나와 주인공 둘이 걷는다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"모험할 때는 다음 목적지만 보게 되잖아."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"가끔은 지금 옆에 있는 사람도 봐. 졸업하고 나면, 이 길을 같이 걷던 애들이 제일 보고 싶어지더라."},
      {"speaker":"주인공","player":true,"text":"선배도 졸업 안 했잖아요."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"미리 아는 거야. 선배니까.","anim":"yuna-laugh"},
      {"speaker":"","text":"교정에 작은 여름 축제. 등불, 노점, 하늘로 올라가는 마법 불꽃.","cut":"ep18-a"},
      {"speaker":"","text":"루스벨과 리안이 불꽃 쏘아 올리기 대결을 한다. 둘 다 점점 크게 쏘다가, 마지막 불꽃이 공중에서 부딪쳐 하트 모양이 된다."},
      {"speaker":"","text":"주변 학생들이 환호한다. 둘은 동시에 얼굴이 시뻘게진다."},
      {"speaker":"루스벨 · 리안","text":"이건 무효야!"},
      {"speaker":"","text":"웃음소리 너머, 솜사탕 노점 앞. 미르엘이 솜사탕을 받아 들다가 학생들과 눈이 마주친다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"……교장도 축제는 즐긴단다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"교수님 입에 설탕 묻었어요.","anim":"doran-think"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"보고서에는 쓰지 말렴."},
    ],
  },
  // ═════════ EP19 · 마법 동아리 합동 실습 ═════════
  19: {
    brief: [
      {"speaker":"","text":"[합동 실습] 훈련장. 카엘이 학생들을 둘씩 짝짓는다. 리안과 루스벨이 같은 조가 된다.","cut":null},
      {"speaker":"리안 · 루스벨","text":"조교님, 바꿔 주세요."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"안 돼. 오늘은 속성의 세기가 아니라, 서로의 타이밍을 본다."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"제일 안 맞는 둘이 맞추면, 나머지는 쉽다."},
    ],
    outro: [
      {"speaker":"","text":"[빛과 어둠의 개념] 실습 자료 마지막 장에 교육과정 밖의 도식이 끼어 있다. 다섯 개의 원 — 화염·빙결·대지, 그리고 빛과 어둠.","cut":null},
      {"speaker":"셀라","portraitId":"comp-sella","text":"이건 빛과 어둠 계열이네. 우리 과정엔 없는 거잖아요."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"3학년 심화 과정 자료가 섞여 들어갔네. 연구 단계다."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"나 이거 조금 배웠어. 빛은 치유랑 보호, 그리고… 감춰진 걸 드러내는 쪽."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"감춰진 걸 드러낸다…… 지워진 글자 같은 것도요?"},
      {"speaker":"유나","portraitId":"comp-yuna","text":"글쎄? 그건 성녀님 정도는 돼야 할걸."},
      {"speaker":"","text":"[학생 토론] 실습 후, 그늘에 앉은 일행.","cut":null},
      {"speaker":"도란","portraitId":"comp-doran","text":"모든 상황에 강한 속성은 없는 것 같아."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그러니까 결국 자기 장점을 잘 쓰는 게 중요하다는 거지."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……아까 네 번째. 네 타이밍 나쁘지 않았어."},
      {"speaker":"리안","portraitId":"comp-rian","text":"어? 어… 너도."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"적어 둬야겠다. 역사적인 날이야.","anim":"sella-think"},
      {"speaker":"도란","portraitId":"comp-doran","text":"날짜 틀리게 적지 마. 요즘 그거 민감해."},
      {"speaker":"","text":"수업이 끝난 뒤. 카엘이 섞여 들어간 3학년 자료를 보관함에 넣고 자물쇠를 채운다.","cut":"ep19-a"},
      {"speaker":"","text":"문서 맨 아래 귀퉁이에 「천공 신전 기록 사본 — 2학년 2학기 열람 예정」이라는 메모가 보인다."},
      {"speaker":"카엘 조교(혼잣말)","portraitId":"npc-kael","text":"……하늘로 가면 결국 보게 될 거다."},
    ],
  },
  // ═════════ EP20 · 여름밤의 성녀 ═════════
  20: {
    brief: [
      {"speaker":"","text":"[방문 소문] 축제 준비로 분주한 중앙광장. 유나가 숨을 헐떡이며 달려온다.","cut":null},
      {"speaker":"유나","portraitId":"comp-yuna","text":"이번 축제에 성녀님이 직접 오신대!"},
      {"speaker":"리안","portraitId":"comp-rian","text":"성녀님이면… 빛 마법 제일 잘하는 사람?"},
      {"speaker":"유나","portraitId":"comp-yuna","text":"제일 잘하는 사람이 아니라, 빛 마법이 '그분 거'인 사람."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……그럼 우리 축제 불꽃 좀 꺼야 하나. 비교되잖아."},
    ],
    outro: [
      {"speaker":"","text":"[첫 대면] 축제 저녁. 하얀 옷의 여인이 호위 없이 노점 사이를 걷는다. 아이들이 그 뒤를 졸졸 따른다.","cut":null},
      {"speaker":"","text":"학생들이 긴장해서 줄을 서자, 성녀 리아나가 먼저 웃는다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"그렇게 굳지 않으셔도 됩니다. 저도 오늘은 축제 손님이에요."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"……그런데 저 꼬치구이는 어디서 파나요? 아까부터 냄새가 너무 좋아서요."},
      {"speaker":"리안","portraitId":"comp-rian","text":"제가 안내할게요!","anim":"rian-laugh"},
      {"speaker":"","text":"꼬치구이 노점 앞. 성녀가 꼬치를 받아 들고 진지하게 한 입 먹는다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"힘은 강한 사람보다 책임지는 사람이 오래 지킵니다. ……그리고 이건 정말 맛있네요."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"명언이랑 맛 평가를 같은 숨에 하셨어.","anim":"sella-think"},
      {"speaker":"","text":"주인공이 해안 사건을 이야기하자, 성녀의 표정이 차분하게 가라앉는다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"바닷속에서 오래된 문을 보았다고요? 문 위에 다른 글자가 덧새겨져 있었고요?"},
      {"speaker":"주인공","player":true,"text":"네. 오웬 사서님이 '누가 나중에 덧쓴 것'이라고 했어요."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"……성역에도 그런 기록이 있어요. 위에 쓴 글자와 아래 글자가 다른 기록들."},
      {"speaker":"","text":"[성녀와 미르엘] 본관 테라스. 성녀와 미르엘이 축제를 내려다보며 차를 마신다. 학생들이 멀찍이서 지켜본다.","cut":null},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"학교 기록과 성역 기록 사이에 차이가 꽤 있는 듯합니다, 교장 선생님."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"오래된 기록은 원래 서로 맞지 않는 법이지요. 그래서 더 흥미롭고요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"우리 학생들이 그걸 찾아냈다니 저도 자랑스럽습니다. 성녀님께서 한번 가르쳐 주시겠어요? 기록을 '읽는' 법을."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"제가요? 영광입니다.","anim":"saint-surprise"},
      {"speaker":"","text":"미르엘이 먼저 성녀를 학교로 초대한다. 둘은 서로를 존중하는 학자처럼 보인다."},
      {"speaker":"","text":"축제가 끝난 밤. 성녀가 혼자 중앙광장 분수대 앞에 선다.","cut":"ep20-a"},
      {"speaker":"","text":"분수 물줄기가 바람에 흩어지며 네 갈래로 갈라진다. 물보라 사이로, 아주 잠깐 오래된 문양이 떠오른다 — 네 개의 원."},
      {"speaker":"","text":"그중 하나가 금빛으로 맺힌다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"이 상징이… 왜 학교에 있지?","anim":"saint-think"},
      {"speaker":"","text":"분수 소리 사이로, 아주 멀리 땅 밑에서 무언가가 한 번 고동친다. 성녀가 발밑을 내려다본다."},
      {"speaker":"","text":"아무것도 없다."},
    ],
  },
  // ═════════ EP21 · 성녀와 첫 대화 ═════════
  21: {
    brief: [
      {"speaker":"","text":"[빛의 수업] 특별 강의실. 미르엘이 성녀를 소개하고 뒷자리에 앉는다.","cut":null},
      {"speaker":"","text":"성녀가 리안의 손등에 난 실습 화상을 빛으로 감싼다. 화상이 천천히 사라진다.","anim":"saint-heal"},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"빛은 공격만을 위한 것이 아닙니다. 치유하고, 보호하고, 감춰진 것을 드러냅니다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……화상 자국 없어졌어. 대박. 한 번 더 데어 와도 돼요?"},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"안 됩니다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"안 된다."},
    ],
    outro: [
      {"speaker":"","text":"[기록 읽기] 성녀가 오웬이 가져온 오래된 문서에 빛을 비춘다. 긁어 지운 자리에서 희미한 글자가 잠깐 떠올랐다 사라진다.","anim":"saint-think","cut":null},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"기록에서는 쓰여 있지 않은 부분도 중요합니다. 지운 자국도 하나의 글이에요. '무엇을 지웠는가'가 남으니까요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……지운 자국도 글이다. 이걸 이십 년 전에 알았으면.","anim":"owen-think"},
      {"speaker":"유나","portraitId":"comp-yuna","text":"사서님, 그 말 오늘 세 번째예요."},
      {"speaker":"","text":"[봉인 질문] 수업이 끝나고, 성녀가 주인공을 따로 부른다.","cut":null},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"해안에서 본 문은 무엇을 잠그고 있었나요?"},
      {"speaker":"주인공","player":true,"text":"아직 모르겠어요."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"그렇다면 확인하면 됩니다."},
      {"speaker":"주인공","player":true,"text":"……그렇게 간단해요?"},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"간단한 것과 쉬운 것은 다릅니다. 이건 간단하지만 쉽진 않을 거예요.","anim":"saint-think"},
      {"speaker":"","text":"빛으로 인장 사본을 비추자, '현재 역사'의 문양 아래로 다른 형태의 문양이 겹쳐 나타난다.","cut":"ep21-a"},
      {"speaker":"","text":"위의 문양은 사슬. 아래의 문양은 — 왕관을 두른 네 개의 원."},
    ],
  },
  // ═════════ EP22 · 중간고사: 빛과 기록 ═════════
  22: {
    brief: [
      {"speaker":"","text":"[시험] 역사·윤리·빛 실기.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"역사를 평가할 때 한쪽 기록만 믿어도 좋겠습니까?"},
      {"speaker":"","text":"답은 '아니다'."},
      {"speaker":"리안","portraitId":"comp-rian","text":"첫 문제 '아니다'잖아. 오웬 사서님이 낸 거면 무조건 '아니다'야."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그 논리로 몇 문제 맞혔어?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"……첫 문제."},
    ],
    outro: [
      {"speaker":"","text":"[윤리 토론] 토론 수업. 성녀가 질문을 던진다.","cut":null},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"적이라는 이유만으로, 그 적에게 하는 모든 행동이 정당해질까요?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"그럼 적이 잘못해도 그냥 봐주자는 건가요?"},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"아닙니다. 잘못은 판단하되, 존재 전체를 잘못으로 묶지는 말자는 겁니다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……근데 사람들은 원래 그렇게 묶잖아요. 어디 출신인지, 무슨 피인지로.","anim":"ruspell-think"},
      {"speaker":"","text":"교실이 조용해진다. 리안이 루스벨을 돌아본다. 루스벨은 창밖을 보고 있다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"그래서 이 수업이 있는 거예요."},
      {"speaker":"","text":"루스벨의 마족 혈통에 대한 첫 암시. 아무도 더 묻지 않는다."},
      {"speaker":"","text":"[미르엘의 마무리]"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"좋은 질문들이었다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"다만 너무 오래된 전쟁을 지금의 감정으로만 판단해서도 안 되겠지. 그때 사람들도 그때의 두려움 속에서 선택했을 테니."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"판단은 늦게, 확인은 빨리. 오늘 토론의 결론은 그거면 충분하구나."},
      {"speaker":"","text":"공정하고 균형 잡힌 마무리. 학생들은 고개를 끄덕인다."},
      {"speaker":"","text":"도서관. 오웬이 오래된 문서를 빛으로 비춘다. '마왕이 먼저 칼을 들었다'라는 문구가 잠시 흐릿해지고, 그 아래로 다른 글자의 획이 비친다.","cut":"ep22-a"},
      {"speaker":"","text":"읽을 수는 없다. 다만 문장의 길이가 다르다. 아래 문장이 훨씬 길다."},
      {"speaker":"사서 오웬(독백)","portraitId":"npc-librarian","text":"……한 줄을 지우고, 더 짧은 한 줄을 썼군."},
    ],
  },
  // ═════════ EP23 · 천공 신전의 문 ═════════
  23: {
    brief: [
      {"speaker":"","text":"[스톰헤이븐 도착] 구름 위로 이어진 돌다리. 바람이 옷자락을 끌어당긴다. 도란이 난간을 두 손으로 붙잡고 있다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"여긴 바다와 달라. 발밑부터 조심해."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……대지 마법사가 땅이 없는 데 오면 어떻게 되는지 알아?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"어떻게 되는데?"},
      {"speaker":"도란","portraitId":"comp-doran","text":"이렇게 돼."},
      {"speaker":"","text":"구름이 걷히며 하늘 도시와 천공 신전이 모습을 드러낸다. 일행이 동시에 숨을 멈춘다."},
    ],
    outro: [
      {"speaker":"","text":"[천공 신전의 손님 (게임 CH3_KING_ENCOUNTER)] 신전 앞뜰. 은빛 갑주의 근위병들이 길을 막는다.","cut":null},
      {"speaker":"왕실 근위병","portraitId":"npc-royal-guard","text":"멈춰라. 지금은 폐하께서 기도를 올리시는 중이다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……폐하? 설마 국왕이요?"},
      {"speaker":"국왕 레오니스","portraitId":"npc-king","text":"괜찮다. 학생들이로구나. 울토르의 교복이군."},
      {"speaker":"국왕 레오니스","portraitId":"npc-king","text":"바람이 거센 날엔 여기 와서 옛 기록을 떠올리곤 하지. 이 나라가 무엇 위에 세워졌는지."},
      {"speaker":"리안","portraitId":"comp-rian","text":"무엇 위에… 세워졌는데요?"},
      {"speaker":"국왕 레오니스","portraitId":"npc-king","text":"전쟁과 승리 위에, 라고 다들 말한다. …나는 가끔 그 말이 너무 깨끗하게 들려서 걱정이다."},
      {"speaker":"","text":"국왕은 짧게 웃고, 근위병들과 함께 신전 안으로 걸어 들어간다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"…방금 그거, 국왕이 할 말 맞아?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"들은 거 보고서에 쓰지 마. 진짜로."},
      {"speaker":"","text":"[벽화] 신전 깊은 곳. 천장까지 닿는 벽화 중앙에 왕관을 쓴 인물이 있다.","cut":null},
      {"speaker":"","text":"왕의 가슴에서 네 개의 상징이 갈라져 나온다. 모두 얼굴 부분만 바람에 깎여 있다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"한 왕의 마음을… 네 갈래로 그렸군요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"공식 역사에는 이런 그림이 없습니다. 이 정도 규모의 벽화가 기록에 한 줄도 없다는 건—"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"누가 일부러 안 적었다는 거죠."},
      {"speaker":"","text":"[폭풍 경보] 일행의 통신 수정구가 울린다. 미르엘이다. 배경에 바람 소리가 섞여 있다.","cut":null},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"스톰헤이븐 관측소에서 폭풍 경보가 왔다. 오늘 조사는 안전 범위까지만 하고 숙소로 돌아가렴."},
      {"speaker":"주인공","player":true,"text":"교수님, 지금 벽화를 찾았어요. 왕의 마음이 넷으로 갈라진 그림이요. 이 신전을 아세요?"},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"문헌으로만. ……너희가 나보다 먼저 직접 봤구나."},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"부럽다. 하지만 바람은 기다려 주지 않는단다. 오늘은 돌아가."},
      {"speaker":"","text":"일행이 떠나기 직전, 벽화의 네 상징 중 하나가 약하게 빛난다 — 금빛.","cut":"ep23-a"},
      {"speaker":"","text":"종소리가 울리고, 빛이 꺼진다. 신전 밖에서 첫 번째 폭풍 돌풍이 몰아친다."},
    ],
  },
  // ═════════ EP24 · 하늘을 올려다보는 이유 ═════════
  24: {
    brief: [
      {"speaker":"","text":"[기말시험] 고대문양 기억 → 빛 마법 → 전투 응용.","cut":null},
    ],
    outro: [
      {"speaker":"","text":"[다음 조사] 도서관. 성녀가 천공 신전 벽화의 탁본과 아틀란티스 대성당의 옛 목록을 나란히 놓는다.","cut":null},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"천공 신전의 기록이 아틀란티스 대성당 지하에도 남아 있을 수 있습니다. 같은 시대, 같은 장인들의 양식이에요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"겨울방학에 확인해 보겠습니다."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"아틀란티스 겨울 엄청 춥대. 바닷바람이 뼈로 들어온대."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"설원보단 낫다."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"조교님은 설원 가 보셨어요?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"아니. 그냥 설원보단 나을 것 같아서."},
      {"speaker":"","text":"[미르엘의 당부] 교장실. 미르엘이 원정 허가서에 서명한다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"보고서는 꼭 제출하렴. 이번에도 제일 먼저 읽고 싶구나."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"그리고 필요 이상으로 오래 머물지는 말고. 겨울 바다는 여름 바다랑 다른 얼굴이란다."},
      {"speaker":"주인공","player":true,"text":"교수님은 아틀란티스 겨울 바다 보신 적 있어요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"……아주 오래전에. 그때도 추웠지."},
      {"speaker":"","text":"기숙사 창가. 주인공이 창밖 하늘을 바라본다. 멀리 구름 사이로 천공 신전이 작게 반짝인다.","cut":"ep24-a"},
      {"speaker":"","text":"동시에 — 아무도 없는 본관 지하, 철문의 문양이 금빛으로 희미하게 반응한다. 입학식 날 밤보다 조금 더 밝게."},
      {"speaker":"","text":"마물 마을의 광장. 아이 마족들이 뿔의 그림자를 둘러싸고 있다. 그녀가 무릎에 아이 하나를 앉혀 옛날이야기를 해 주고 있다.","cut":"ep24-b"},
      {"speaker":"아이 마족","text":"그래서 그 왕은 어떻게 됐어요?"},
      {"speaker":"뿔의 그림자","text":"……음. 오늘은 여기까지 하자꾸나."},
      {"speaker":"아이 마족","text":"에이! 맨날 거기서 끊어!"},
      {"speaker":"뿔의 그림자","text":"끝을 잘 몰라서 그렇단다."},
      {"speaker":"","text":"아이들이 웃으며 흩어진다. 그녀가 혼자 남아 자기 가슴께에 손을 얹는다."},
      {"speaker":"","text":"손바닥 아래에서, 아주 작은 금빛이 반딧불처럼 한 번 깜빡인다."},
      {"speaker":"뿔의 그림자","text":"……너였구나. 아직 거기 있었구나."},
      {"speaker":"","text":"화면 암전."},
    ],
  },
  // ═════════ EP25 · 대성당으로 가는 겨울길 ═════════
  25: {
    brief: [
      {"speaker":"","text":"[성당 입구] 눈이 내리는 아틀란티스. 수로 위에 얇은 얼음이 떠다닌다. 하얀 대성당의 종탑 끝에 눈이 쌓여 있다.","cut":null},
      {"speaker":"","text":"성녀가 성당 계단에서 일행을 맞는다. 코끝이 빨갛다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"이번에는 연구자라는 마음보다, 누군가를 만나러 왔다고 생각해 주세요."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"누구를요?"},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"이 성당에 남아 있는, 오래전 사람들의 마음을요."},
      {"speaker":"","text":"유나가 주변을 살핀다. 성당 앞 광장에 사람이 거의 없다."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"생각보다 조용하네. 축제 때랑 완전 다른 도시 같아."},
      {"speaker":"브라더 모렌","text":"겨울엔 바다도 사람도 웅크리지요. 들어오세요. 수프가 식기 전에."},
    ],
    outro: [
      {"speaker":"","text":"[생활 봉사] 성당과 주민들의 겨울 지원. 장작 나르기, 무료 급식, 아이들 돌보기.","cut":null},
      {"speaker":"","text":"유나가 아이들에게 빛 마법으로 작은 별을 만들어 보여 준다. 오웬은 장작을 나르다가 세 번 쉰다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"사서는… 책보다 무거운 걸 들지 않는 직업입니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"사서님, 그거 장작 두 개예요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"젖은 장작입니다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"역사를 찾는 일도 결국 사람을 위한 일이어야 합니다. 오늘 하루는 그걸로 충분해요.","anim":"saint-laugh"},
      {"speaker":"","text":"[왕의 부조] 밤. 브라더 모렌이 촛불을 들고 일행을 지하 예배실로 안내한다.","cut":null},
      {"speaker":"","text":"\"오래돼서 아무도 안 내려오는 방\"이라고 했다. 벽 한 면을 차지한 부조가 촛불에 드러난다."},
      {"speaker":"","text":"왕관을 쓴 인물. 교과서 속 마왕의 뿔과 같은 뿔. 그러나 표정은 온화하고, 두 팔은 무언가를 감싸 안고 있다."},
      {"speaker":"","text":"그 품에 안긴 것은 인간 아이와 마족 아이다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"이건… 모르스일 가능성이 높습니다.","anim":"owen-surprise"},
      {"speaker":"브라더 모렌","text":"저희는 그냥 '뿔 달린 성인'이라고 불렀습니다. 누군지는 아무도 몰랐어요."},
      {"speaker":"유나","portraitId":"comp-yuna","text":"마왕이… 애들을 안고 있어.","anim":"yuna-think"},
      {"speaker":"","text":"부조 속 왕의 손등에 새겨진 네 개의 원. 그중 하나가 촛불도 없는데 푸르게 빛난다. 눈물방울 모양으로.","cut":"ep25-a"},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"이 기록은 왕의 힘이 아니라, 왕의 마음을 남겼어요."},
    ],
  },
  // ═════════ EP26 · 네 개로 나뉜 마음 ═════════
  26: {
    brief: [
      {"speaker":"","text":"[지하 벽화] 부조 뒤편의 숨겨진 통로. 더 깊은 방의 벽 전체가 하나의 벽화다.","cut":null},
      {"speaker":"","text":"왕의 몸에서 네 가지 색의 빛이 갈라져 나간다. 각 빛 안에는 서로 다른 표정이 그려져 있다."},
      {"speaker":"","text":"웃는 얼굴. 이를 악문 얼굴. 우는 얼굴. 그리고 — 장난스럽게 혀를 내민 얼굴."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"감정… 네 개의 감정이 따로 그려져 있어요."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……저건 메롱 하는 거죠?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"학술적으로는 '즐거움'의 표현으로 보입니다. 메롱이 맞습니다.","anim":"owen-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"하지만 이름은 전부 잘려 있습니다. 네 개 모두, 정으로 쪼아 냈어요."},
    ],
    outro: [
      {"speaker":"","text":"[오웬의 가설] 방 한가운데 앉아, 오웬이 노트를 펼친다. 촛불이 흔들린다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"단순한 상징이 아니라, 인격의 일부일 가능성이 있습니다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"기쁨, 분노, 슬픔, 즐거움. 옛말로 희·노·애·락."},
      {"speaker":"주인공","player":true,"text":"왕의 마음이 여러 조각으로 나뉜다는 건가요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"가설일 뿐입니다. 하지만 '봉인'과 함께 생각하면… 하나를 넷으로 나눠 따로 가두는 편이, 통째로 가두는 것보다 훨씬 쉽습니다."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"사람을 넷으로 나눈다니. 그건 봉인이 아니라… 해부예요.","anim":"saint-think"},
      {"speaker":"","text":"정적. 셀라가 노트를 꼭 쥔다."},
      {"speaker":"","text":"[학교의 흔적] 벽화 뒤 석판 아래쪽. 촛농을 걷어 내자 작은 문장이 드러난다. 펜과 열쇠가 교차한 문양.","cut":null},
      {"speaker":"","text":"일행이 모두 아는 문장이다. 울토르 도서관 정문 위에 새겨진 것과 같다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"이거… 울토르 문장이잖아요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"정확히는 '울토르 기록관'의 옛 문장입니다. 지금은 쓰지 않아요. 기록관 제도는 이백 년 전에 폐지됐으니까요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……왕립 기록원의 교정 도장, 그리고 울토르 기록관. 우리 학교가, 오래전에 이 기록들에 손을 댔다는 뜻입니다."},
      {"speaker":"주인공","player":true,"text":"사서님이 그 기록관의……"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"네. 후임자죠. 이백 년 늦은.","anim":"owen-sad"},
      {"speaker":"","text":"벽화의 왕관 부분. 원래 이름이 있었던 자리에 홈이 긁혀 있다. 그 아래 기록관 문장이 '확인 완료'의 표시처럼 찍혀 있다.","cut":"ep26-a"},
      {"speaker":"","text":"오웬이 그 문장을 손끝으로 쓸어 본다. 자기 도서관 열쇠고리에 달린 것과 같은 모양이다."},
    ],
  },
  // ═════════ EP27 · 읽지 못한 문장 ═════════
  27: {
    brief: [
      {"speaker":"","text":"[해독 실패] 성녀가 벽화 아래 고대 문장에 오래도록 빛을 비춘다. 이마에 땀이 맺힌다.","anim":"saint-think","cut":null},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"일부만 드러나고 있어요. 글자의 모양은 보이는데… 뜻이 보이지 않아요."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"우리 문자 체계보다 훨씬 오래됐습니다. 해저 문, 천공 신전, 그리고 이 벽화. 전부 같은 문자예요. 그리고 전부 읽을 수 없습니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그 시대 문자를 아는 사람이 이 세상에 한 명도 없는 거예요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"적어도 살아 있는 사람 중에는."},
    ],
    outro: [
      {"speaker":"","text":"[중단 지시] 통신 수정구가 울린다. 미르엘이다.","cut":null},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"아틀란티스 해안에 폭풍 해일 경보가 내려졌다. 겨울 원정은 여기까지 하자꾸나."},
      {"speaker":"주인공","player":true,"text":"하지만 아직 읽지 못한 부분이—"},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"알고 있다. 아쉬운 거, 나도 안다."},
      {"speaker":"미르엘 교수(통신)","portraitId":"npc-mirel","text":"하지만 해일은 기록을 기다려 주지 않고, 나는 학생을 잃을 생각이 없단다. 탁본은 전부 가져오렴. 학교에서 같이 보자."},
      {"speaker":"","text":"통신이 끊긴다."},
      {"speaker":"","text":"[결심] 돌아가는 배. 갑판 위에 눈이 쌓인다.","cut":null},
      {"speaker":"셀라","portraitId":"comp-sella","text":"다음에는 우리가 직접 확인해요. 유물이 있는 곳으로."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"그렇게 합시다. 기록이 허락하는 만큼이 아니라, 유물이 보여 주는 만큼."},
      {"speaker":"성녀 리아나","portraitId":"npc-saint","text":"그때는 저도 함께하겠습니다. 이건 이제 성역의 일이기도 하니까요."},
      {"speaker":"","text":"배가 크게 흔들린다. 오웬이 탁본 통을 껴안고 휘청인다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"……통은 무사합니다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"사서님은요?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"통이 무사하면 저도 무사합니다."},
      {"speaker":"","text":"울토르 도서관. 밤. 오웬이 가져온 탁본들을 벽 하나에 전부 붙인다.","cut":"ep27-a"},
      {"speaker":"","text":"해저 문, 천공 신전, 대성당 벽화. 같은 문자, 같은 네 개의 원."},
      {"speaker":"","text":"그리고 그 옆에 한 줄의 메모: 「읽지 못하는 것은 우리만이 아니다. '읽지 못하게 만든' 사람이 있다.」"},
    ],
  },
  // ═════════ EP28 · 천공 아래서 찾은 길 ═════════
  28: {
    brief: [
      {"speaker":"","text":"[고급 탐사 수업] 3학년 첫 수업. 카엘이 정식 조교 겸 강사로 교단에 선다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"3학년부터는 찾는 능력보다 확인하는 능력이 중요하다."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"찾는 건 운이고, 확인하는 건 실력이야."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"둘 다 하면요?"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"졸업."},
      {"speaker":"","text":"실제 지도와 유물 데이터를 마법 투영판 위에 겹쳐 본다."},
    ],
    outro: [
      {"speaker":"","text":"[폐허의 좌표] 천공 신전 벽화의 별자리 배치를 지도에 겹치자, 한 점이 빛난다.","cut":null},
      {"speaker":"","text":"왕국 남서쪽, '버려진 폐허'라 불리는 곳의 입구와 정확히 일치한다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"하늘 위의 문양이 여기에도 있습니다. 숲, 바다, 하늘… 그리고 땅 아래."},
      {"speaker":"리안","portraitId":"comp-rian","text":"폐허면… 언데드 나오는 데잖아요."},
      {"speaker":"도란","portraitId":"comp-doran","text":"응."},
      {"speaker":"리안","portraitId":"comp-rian","text":"또 '응'이야."},
      {"speaker":"","text":"[미르엘의 승인] 교장실. 미르엘이 투영된 좌표를 오래 들여다본다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"버려진 폐허라. 위험한 곳이다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"……그래도 너희가 여기까지 왔으니, 이번엔 현장을 직접 확인하도록 하자. 정식 실습으로 등록해 주마. 그래야 사고가 나도 학교가 책임질 수 있으니까."},
      {"speaker":"리안","portraitId":"comp-rian","text":"사고 나는 거 전제예요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"리안이 가니까."},
      {"speaker":"","text":"무너진 성문 너머로 버려진 신전의 실루엣. 안개가 신전을 휘감고 있다.","cut":"ep28-a"},
      {"speaker":"","text":"문 위의 네 원 문양 중 하나가 희미하게, 붉게 빛난다. 지금까지 본 것들과 달리 — 따뜻하지 않다."},
    ],
  },
  // ═════════ EP29 · 중간고사: 고대마법과 역사의 빈칸 ═════════
  29: {
    brief: [
      {"speaker":"","text":"[종합 시험] 고대문양 배열, 영창 암기, 역사 문제, 실전 과제.","cut":null},
      {"speaker":"","text":"마지막 문제. 출제자: 미르엘."},
      {"speaker":"","text":"서로 충돌하는 기록이 있다면, 무엇을 우선해야 하는가? 이유와 함께 서술하시오."},
      {"speaker":"","text":"시험장에 펜 소리가 멈춘다. 학생들이 오래 생각한다."},
      {"speaker":"","text":"주인공 옆자리, 리안이 답안지에 무언가를 열심히 쓰다가 지우고, 또 쓴다."},
    ],
    outro: [
      {"speaker":"","text":"[오웬의 질문] 시험이 끝난 뒤, 도서관 계단.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"교과서와 유물이 다르면, 무엇을 믿겠습니까?"},
      {"speaker":"주인공","player":true,"text":"둘 다 확인해야죠. 누가, 언제, 왜 썼는지."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"좋은 답입니다. 미르엘 교수님 수업을 제대로 들으셨군요.","anim":"owen-surprise"},
      {"speaker":"리안","portraitId":"comp-rian","text":"저도 비슷하게 썼어요. '둘 다 믿되, 반만 믿는다.'","anim":"rian-laugh"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……그건 철학이야, 답이야?"},
      {"speaker":"리안","portraitId":"comp-rian","text":"부분 점수."},
      {"speaker":"","text":"[현장실습 명분] 카엘이 폐허 조사를 정식 실습 과제로 게시판에 붙인다. 「3학년 현장실습: 버려진 폐허 기록 대조 — 지원자 모집」","cut":null},
      {"speaker":"","text":"일행의 이름이 첫 줄부터 차례로 적힌다."},
      {"speaker":"","text":"채점실. 미르엘이 마지막 문제의 답안지들을 넘긴다. 리안의 답안에서 손이 멈춘다.","cut":"ep29-a"},
      {"speaker":"","text":"「둘 다 믿되, 반만 믿는다. 왜냐하면 둘 다 사람이 썼으니까.」"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"……이번엔 이유를 썼구나.","anim":"mirel-laugh"},
      {"speaker":"","text":"여백에 동그라미 하나. 그리고 1학년 때와 같은 글씨로, 한 단어. 「좋다.」"},
      {"speaker":"","text":"리안의 성장을 보여 주는 장면. 미르엘은 좋은 교사로 보인다."},
    ],
  },
  // ═════════ EP30 · 버려진 폐허의 기록자 ═════════
  30: {
    brief: [
      {"speaker":"","text":"[묘지의 기록] 안개 낀 폐허. 무너진 아치 아래로 이름이 닳아 없어진 묘비들이 줄지어 있다.","cut":null},
      {"speaker":"","text":"한 묘비 앞에서 잉크병을 든 반투명한 노인이 떠오른다. 언데드 기록자다. 깃펜을 쥔 손가락이 뼈만 남았다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……저건 말 안 하는 쪽이었으면 좋겠다."},
      {"speaker":"언데드 기록자","text":"살아 있는 자는… 자기 이야기를 남긴다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"말하는 쪽이네."},
      {"speaker":"도란","portraitId":"comp-doran","text":"요즘 다 말해."},
    ],
    outro: [
      {"speaker":"","text":"[기록의 시험] 기록자가 세 권의 장부를 허공에 펼친다. 같은 날의 같은 사건이 서로 다르게 적혀 있다.","cut":null},
      {"speaker":"언데드 기록자","text":"셋 중 둘은 고친 것이다. 고친 자국을 찾아라. 찾으면 문을 열어 주마."},
      {"speaker":"","text":"세 개의 기록 중 서로 모순되는 부분을 찾는 퀴즈."},
      {"speaker":"","text":"성공 시 기록자가 깃펜으로 허공에 선을 긋고, 무너진 아치 뒤의 문이 열린다."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"같은 일을 하던 분이시군요."},
      {"speaker":"언데드 기록자","text":"……사서인가. 반납 기한은 지키나?"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"목숨처럼."},
      {"speaker":"언데드 기록자","text":"좋다."},
      {"speaker":"","text":"[승자의 기록] 열린 문 너머, 무너진 서고. 반쯤 탄 책들이 바닥에 쌓여 있다.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"당신은 무엇을 남기려 했습니까?"},
      {"speaker":"언데드 기록자","text":"있었던 일."},
      {"speaker":"언데드 기록자","text":"승자는 자신이 옳았다고 적는다. 그건 죄가 아니다. 다들 그렇게 한다."},
      {"speaker":"언데드 기록자","text":"죄는, 진 쪽의 기록을 태우는 것이다. 그러면 남는 건 한쪽의 이야기뿐이니까."},
      {"speaker":"언데드 기록자","text":"그러니 네가 배운 것을 믿기 전에… 누가 적었는지, 그리고 누가 태웠는지 물어라."},
      {"speaker":"","text":"기록자의 기억. 오래전 이 서고. 회색 망토를 입은 사람들이 특정 책장만 골라 불태운다.","cut":"ep30-a"},
      {"speaker":"","text":"불길 속에서 기록자가 장부 한 권을 품에 안고 쓰러진다."},
      {"speaker":"","text":"그 장부가 지금, 잿더미 속에 남아 있다. 표지에는 울토르 기록관의 옛 문장 — 펜과 열쇠."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……태운 쪽도 이 문장을 달고 있었어. 지킨 쪽도.","anim":"sella-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"같은 기관 안에서도 서로 다른 선택을 했던 겁니다."},
    ],
  },
  // ═════════ EP31 · 신전으로 이어지는 균열 ═════════
  31: {
    brief: [
      {"speaker":"","text":"[기말 실습] 고대문양, 봉인 안전해제, 전투 실습. 카엘의 봉인 해제 실습에서 리안이 자물쇠 대신 책상을 녹인다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"……봉인 해제라고 했지, 봉인 소각이라고 안 했다."},
    ],
    outro: [
      {"speaker":"","text":"[신전 아래의 원형 방] 기록자의 장부에 그려진 지도를 따라, 무너진 신전 바닥 아래 숨겨진 원형 방에 도착한다.","cut":null},
      {"speaker":"","text":"방 중앙에 네 개의 받침대. 공기가 무겁고, 이상하게 따뜻하다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"중앙에 뭔가가 있었던 흔적이 있어. 사람이 앉아 있던 것 같은 자국.","anim":"sella-think"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"정확히는… 사람의 일부였을지도 모릅니다. 대성당 벽화의 '넷으로 나뉜 마음'처럼."},
      {"speaker":"리안","portraitId":"comp-rian","text":"그런 말 이런 데서 하지 마세요. 소름 돋잖아요."},
      {"speaker":"","text":"[미르엘의 도착] 계단 위에서 다급한 발소리. 미르엘이 망토 자락을 걷어 쥐고 내려온다. 숨이 차 있다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"카엘 조교 보고를 받았다. 폐허 지하에 학생들끼리 내려갔다고."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"……모두 무사하구나. 다행이다."},
      {"speaker":"주인공","player":true,"text":"교수님, 이 신전을 아세요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"문헌에서 본 적이 있단다. 봉인학 고서에 '네 개의 자리'라는 그림이 있었지. 실물을 보는 건 처음이구나."},
      {"speaker":"리안","portraitId":"comp-rian","text":"교수님은 문헌으로 안 보신 게 뭐예요?","anim":"rian-think"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"리안의 기말 답안 같은 거.","anim":"mirel-think"},
      {"speaker":"","text":"셀라가 웃음을 참다가 기침을 한다. 긴장이 조금 풀린다.","anim":"sella-laugh"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"오늘은 여기까지. 이 방은 봉인학 전문가 없이 더 건드리면 안 된다. 다음 원정은 내가 직접 준비를 도우마."},
      {"speaker":"","text":"일행이 떠난 뒤, 빈 방. 네 개의 자리 중 세 곳은 오래전에 비어 먼지만 쌓여 있다.","cut":"ep31-a"},
      {"speaker":"","text":"남은 한 자리만 검붉게 갈라져 있다. 갈라진 틈에서 아주 약한 열기가 숨처럼 새어 나온다."},
    ],
  },
  // ═════════ EP32 · 방학 원정, 마지막 평온 ═════════
  32: {
    brief: [
      {"speaker":"","text":"[캠프 준비] 출발 전 학교 정문. 반과 셀린이 보급품을 나눠 준다.","cut":null},
      {"speaker":"반","portraitId":"npc-weapon","text":"부서지면 돌아와서 말해."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"아프면 참지 말고. 참는 건 용기가 아니라 미련이야."},
      {"speaker":"리안","portraitId":"comp-rian","text":"두 분 다 엄마 같아요.","anim":"rian-laugh"},
      {"speaker":"반","portraitId":"npc-weapon","text":"……난 아빠 쪽이다."},
      {"speaker":"셀린","portraitId":"npc-potion","text":"그건 아무도 안 물어봤어요, 반 선생님."},
      {"speaker":"","text":"뒤쪽에서 루스벨이 커다란 배낭을 메고 나타난다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"카엘 조교님이 화염 쪽 인원 하나 더 필요하다고 해서. 나 빼면 화염은 리안뿐이잖아. 그건 좀 불안하지."},
      {"speaker":"리안","portraitId":"comp-rian","text":"야!"},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"맞는 말이다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"조교님까지?!"},
    ],
    outro: [
      {"speaker":"","text":"[식사와 제작] 폐허 외곽의 야영지. 요리/장비 제작으로 모험 전 마지막 정비.","cut":null},
      {"speaker":"","text":"루스벨이 손바닥 불꽃으로 고기를 굽는다. 리안이 질세라 옆에서 같이 굽는다. 고기가 두 배로 빨리 탄다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……화염 두 명은 요리에 해로워."},
      {"speaker":"","text":"[졸업 후 이야기] 모닥불. 별이 쏟아진다.","cut":null},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"졸업하면 어디로 갈지 생각해 본 적 있어?"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"기록 쪽이요. 오웬 사서님 밑에서 일하고 싶어요. ……지워진 걸 다시 쓰는 일."},
      {"speaker":"도란","portraitId":"comp-doran","text":"고향 돌아가서 산사태 막는 일. 우리 동네 매년 무너져."},
      {"speaker":"리안","portraitId":"comp-rian","text":"난 아직 몰라. 근데 뭘 하든 1등 할 거야."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……난 그냥, 아무도 내 피 얘기 안 하는 곳.","anim":"ruspell-think"},
      {"speaker":"","text":"모닥불이 탁 튄다. 다들 루스벨을 본다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"왜. 다들 알잖아. 우리 외할머니 쪽이 화염 마족인 거. 입학 서류에도 적혀 있어.","anim":"ruspell-laugh"},
      {"speaker":"리안","portraitId":"comp-rian","text":"……그래서 불꽃이 그렇게 센 거였어? 반칙이네."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"응. 반칙이야. 억울하면 너도 할머니 바꿔.","anim":"ruspell-laugh"},
      {"speaker":"","text":"웃음이 번진다. 루스벨이 처음으로 편하게 웃는다."},
      {"speaker":"","text":"모닥불 주위의 평범한 밤. 카메라가 천천히 멀어져 어둠 속 신전 입구를 비춘다.","cut":"ep32-a"},
      {"speaker":"","text":"돌 틈에서 아주 작은 균열이 생긴다. 균열 사이로 붉은빛이 한 번, 맥박친다."},
      {"speaker":"","text":"모닥불 앞, 잠든 루스벨이 이마를 찡그린다. 꿈속에서 누군가에게 대답하듯 입술이 움직인다."},
    ],
  },
  // ═════════ EP33 · 죽은 자가 기억하는 전쟁 ═════════
  33: {
    brief: [
      {"speaker":"","text":"[전쟁의 환영] 폐허 심층부. 발을 들이는 순간 주변 풍경이 바뀐다. 오백 년 전의 전장.","cut":null},
      {"speaker":"","text":"인간 병사도, 마족 병사도 똑같이 떨고 있다. 누가 먼저 활을 쏘았는지 아무도 모른다. 둘 다 상대가 먼저 쐈다고 소리친다."},
      {"speaker":"도란","portraitId":"comp-doran","text":"……다들 무서워하고 있어. 양쪽 다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"여기 너무 더워. 다들 안 더워?","anim":"ruspell-heat"},
      {"speaker":"셀라","portraitId":"comp-sella","text":"……환영 속이라 오히려 추운데."},
    ],
    outro: [
      {"speaker":"","text":"[언데드 마법사] 전장 한가운데, 부서진 지팡이를 짚은 언데드 마법사가 서 있다.","cut":null},
      {"speaker":"언데드 마법사","text":"너희는 승자의 이야기를 배웠군."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"당신은 어느 편이었습니까?"},
      {"speaker":"언데드 마법사","text":"기억하는 편."},
      {"speaker":"언데드 마법사","text":"그 전쟁에서 인간 쪽이었고, 마족 쪽에 친구가 있었다. 둘 다 그날 죽었지. 그래서 둘 다 기억한다."},
      {"speaker":"리안","portraitId":"comp-rian","text":"……그럼 누가 먼저 공격했는데요?"},
      {"speaker":"언데드 마법사","text":"누가 먼저 공격하게 '만들었는지'를 물어야지."},
      {"speaker":"","text":"[두 개의 기록] 언데드 마법사가 두 권의 기록을 펼친다. 하나는 왕국 공식 기록. 하나는 이름 없는 병사의 일기.","cut":null},
      {"speaker":"","text":"'누가 먼저 공격했는가'를 정반대로 서술한다."},
      {"speaker":"카엘 조교","portraitId":"npc-kael","text":"둘 중 하나는 거짓말이군."},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"혹은 둘 다 일부만 진실일 수도 있습니다. 하지만—"},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"공식 기록에는 그날 날씨가 '맑음'이고, 병사의 일기에는 '폭우'입니다. 폭우 속에서 화살은 멀리 못 갑니다. 공식 기록의 전투는… 일어날 수 없는 전투예요."},
      {"speaker":"","text":"환영이 바뀐다. 불타는 왕도. 뿔 달린 왕이 성문 앞에서 피난민들을 — 인간과 마족 모두를 — 먼저 성 밖으로 내보낸다.","cut":"ep33-a"},
      {"speaker":"","text":"왕은 마지막으로 성 안을 한 번 돌아보고, 홀로 남는다. 성문이 닫힌다."},
      {"speaker":"주인공","player":true,"text":"저 왕… 모르스 아니야?"},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……'다 나갔느냐'.","anim":"ruspell-think"},
      {"speaker":"리안","portraitId":"comp-rian","text":"뭐?"},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"어? 나 지금 뭐라고 했어?"},
      {"speaker":"","text":"아무도 대답하지 못한다. 환영이 사라진다."},
    ],
  },
  // ═════════ EP34 · 문을 열지 말 것 ═════════
  34: {
    brief: [
      {"speaker":"","text":"[신전문] 버려진 신전 정문. 거대한 석문 위에 세 가지 문자로 같은 경고가 새겨져 있다. 고대문자, 옛 공용문자, 그리고 현대 문자.","cut":null},
      {"speaker":"사서 오웬","portraitId":"npc-librarian","text":"문을 열지 말 것."},
      {"speaker":"리안","portraitId":"comp-rian","text":"이렇게 써 놓으면 더 열고 싶잖아."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"그래서 세 번이나 써 놓은 거야. 너 같은 사람 때문에."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……이 안, 진짜 뜨거워. 문 너머에서 열이 나와.","anim":"ruspell-heat"},
      {"speaker":"도란","portraitId":"comp-doran","text":"차가운데."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……나만 그래?"},
    ],
    outro: [
      {"speaker":"","text":"[미르엘의 허가] 야영지. 미르엘이 직접 봉인학 장비를 들고 합류한다. 카엘이 보낸 보고서를 손에 들고 있다.","cut":null},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"들어가도 된다."},
      {"speaker":"셀라","portraitId":"comp-sella","text":"왜 갑자기 허가하시는 거죠? 지난번엔 건드리면 안 된다고 하셨잖아요."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"지난번엔 봉인학 전문가가 없었지. 이번엔 내가 있다."},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"그리고 저 문 안쪽 봉인이 약해지고 있다. 카엘 조교 측정치를 보니 매주 조금씩 열이 오르고 있더구나. 그대로 두면 언젠가 저절로 깨진다. 그 전에 안에서 다시 묶어야 해."},
      {"speaker":"주인공","player":true,"text":"위험하지 않아요?"},
      {"speaker":"미르엘 교수","portraitId":"npc-mirel","text":"위험하지. 그러니 내가 앞장서고, 내가 책임지마."},
      {"speaker":"","text":"믿음직한 어른. 학생들의 어깨에서 힘이 빠진다."},
      {"speaker":"루스벨","portraitId":"comp-rusbel","text":"……교장 선생님 있으면 괜찮겠지?","anim":"ruspell-think"},
      {"speaker":"리안","portraitId":"comp-rian","text":"당연하지. 저분 오백 살은 먹은 것처럼 아는 게 많잖아."},
      {"speaker":"","text":"농담이다. 아무도 웃지 않을 이유가 없다. 다들 웃는다."},
      {"speaker":"","text":"석문이 아주 조금 열린다. 틈 사이로 뜨거운 바람이 새어 나온다.","cut":"ep34-a"},
      {"speaker":"","text":"그리고 누군가의 속삭임. 낮고, 갈라지고, 화가 난 목소리."},
      {"speaker":"","text":"……돌아가."},
      {"speaker":"","text":"신전 내부의 검붉은 빛이 한 번 깜빡인다."},
      {"speaker":"","text":"루스벨만 그 자리에 굳어 선다. 그녀의 귀에는 다른 말이 들렸다."},
      {"speaker":"","text":"……와라."},
    ],
  },
}

export const CUTSCENES_GEN: CutsceneDef[] = [
  {"id":"ep05-a","scene":"EP05 [CUTSCENE 05-A] 새벽의 고목숲","full":false,"shot":"야영지의 불이 꺼진 뒤, 카메라가 숲 위로 떠오른다. 뿌리 사이로 금빛 섞인 검은빛이 하나씩 점멸한다. 반딧불이처럼, 그러나 반딧불이보다 느리게. 빛은 고목숲 가장 깊은 곳으로 흘러간다. 나무 아래, 지난 학기 뿌리에서 본 것과 같은 원형 문양이 이끼에 반쯤 덮여 있다. 텐트 하나에서 리안의 잠꼬대가 들린다. 화면 암전.","refs":["리안 삼면도.jpg","스토리 NPC 일러스트.png"]},
  {"id":"ep06-a","scene":"EP06 [CUTSCENE 06-A] 모닥불과 편지","full":false,"shot":"밤. 캠프. 모닥불 앞에서 셀린이 변이핵 분석 메모를 쓰고, 오웬은 통신 수정구로 학교에 보고한다. 통신이 끊긴다. 리안이 모닥불 너머로 소리친다. 셀라가 웃음을 참느라 노트로 얼굴을 가린다. 노트에는 오늘 날짜와 함께 한 줄이 적혀 있다. 「쓰러진 변이체 → 꽃. 마력이 '죽지' 않는다. 어디로 가는가?」","refs":["리안 삼면도.jpg","전투 NPC 셀라 삼면도.png","스토리 NPC 일러스트.png"]},
  {"id":"ep07-a","scene":"EP07 [CUTSCENE 07-A] 방학 마지막 밤","full":false,"shot":"모닥불. 세 동료가 이번 원정을 돌아본다. 불티가 별 사이로 올라간다. 모닥불이 탁 튄다. 아무도 한동안 말이 없다.","refs":[]},
  {"id":"ep07-b","scene":"EP07 [INTERLUDE 07-B] 같은 시각, 화산지대 (막간)","full":true,"shot":"용암 온천. 김이 자욱하다. 거대한 뿔의 그림자가 어깨까지 몸을 담그고 있다. 옆에서 작은 날개 달린 수하가 장기판을 들고 종종걸음으로 온다. 온천 바닥의 바위틈이 은은한 금빛으로 물든다. 같은 순간 — 아주 먼 남쪽, 무너진 골렘의 방에서 꺼졌던 금빛 맥박이 다시 한 번, 약하게 뛴다. 화면 암전.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png"]},
  {"id":"ep08-a","scene":"EP08 [CUTSCENE 08-A] 바다 전환","full":false,"shot":"숲을 빠져나와 언덕을 넘는 주인공 시점. 숲의 녹음이 뒤로 물러나고, 화면이 한꺼번에 넓어진다. 끝없는 푸른 바다. 소금 냄새가 화면 너머로 느껴질 것처럼 바람이 분다. 리안이 언덕 위에서 두 팔을 벌린다. 짧은 순간, 물결 위에 고목에서 본 원형 문양이 비친다. 아무도 보지 못한다.","refs":["리안 삼면도.jpg"]},
  {"id":"ep09-a","scene":"EP09 [CUTSCENE 09-A] 겨울 바다의 전조","full":false,"shot":"밤. 해안 마을의 집들이 하나둘 창문을 닫는다. 덧문 닫히는 소리가 파도 소리를 따라 번진다. 수평선 아래에서 푸른빛이 솟는다. 한 번. 두 번. 세 번. 빛이 솟을 때마다 바다 전체가 숨을 들이쉬는 것처럼 조용해진다. 카메라가 물속으로 내려간다. 빛을 따라 아래로, 더 아래로. 해저 깊은 곳에 거대한 돌문이 짧게 보인다. 문 표면의 원형 홈 하나가 빛에 맞춰 떨리고 있다. 화면 암전.","refs":[]},
  {"id":"ep10-a","scene":"EP10 [CUTSCENE 10-A] 수면 아래의 문","full":false,"shot":"해저 계단 끝. 주인공이 돌문 표면에 손을 대자, 네 개의 원형 홈이 잠깐 빛난다. 그중 하나 — 숲의 돌판에서 금으로 덧칠되어 있던 바로 그 자리 — 가 가장 밝다. 물결이 거꾸로 흐르는 것처럼 보이고, 문이 아주 미세하게 떨린다. 문은 열리지 않는다. 떨림이 천천히 가라앉는다.","refs":[]},
  {"id":"ep11-a","scene":"EP11 [CUTSCENE 11-A] 파도 아래 잠든 것","full":false,"shot":"화면이 둘로 갈라진다. 왼쪽은 에르디아 숲 깊은 곳의 원형 문양, 오른쪽은 해저 돌문의 원형 홈. 둘이 동시에 빛난다. 빛줄기가 서로를 향해 뻗어 — 연결되려는 순간, 끊어진다. 그리고 아주 잠깐, 두 빛줄기가 같은 방향을 가리킨다. 북쪽.","refs":[]},
  {"id":"ep12-a","scene":"EP12 [CUTSCENE 12-A] 겨울 바다의 불빛","full":false,"shot":"카메라가 수면 아래로 내려간다. 거대한 광원이 해저 깊은 곳에서 맥박친다. 그 아래, 반쯤 모래에 잠긴 돌문. 문의 네 홈 중 하나가 광원과 같은 박자로 깜빡인다.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep12-b","scene":"EP12 [INTERLUDE 12-B] 같은 시각, 화산지대 (막간)","full":true,"shot":"용암이 흐르는 마을 외곽의 작은 밭. 화산재 흙에 무언가가 줄지어 심겨 있다. 거대한 뿔의 그림자가 쪼그려 앉아 새싹 하나를 들여다본다. 뒤에서 덩치 큰 수하가 물뿌리개를 들고 있다. 그녀가 손끝으로 새싹을 건드린다. 새싹이 쑥, 손가락 한 마디만큼 자란다. 덩치 큰 수하가 물뿌리개를 떨어뜨린다. 화면 암전.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png"]},
  {"id":"ep13-a","scene":"EP13 [CUTSCENE 13-A] 심해의 문","full":false,"shot":"돌문이 아주 조금 열렸다가, 스스로 닫힌다. 문틈 너머로 아주 짧게 — 어둠이 아니라 따뜻한 빛이 새어 나온다. 그 빛은 어딘가 슬퍼 보인다.","refs":[]},
  {"id":"ep14-a","scene":"EP14 [CUTSCENE 14-A] 기억과 교과서","full":false,"shot":"화면에 해저에서 본 기억 속 왕의 실루엣과, 학교 교과서 속 '마왕 모르스' 삽화가 겹친다. 기억 속 왕은 아이에게 손을 흔들고 있다. 교과서 속 마왕은 불타는 도시 위에서 포효하고 있다. 같은 왕관. 같은 뿔. 정반대의 얼굴. 독백이 끊긴다. 오웬이 스스로 생각을 멈춘다. 셋이 피식 웃는다. 웃음이 오래가지 않는다.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png","스토리 NPC 일러스트.png"]},
  {"id":"ep15-a","scene":"EP15 [CUTSCENE 15-A] 도서관의 밤","full":false,"shot":"밤의 도서관. 오웬 혼자 공식 역사서 『울토르 왕국사』 원본을 펼친다. 인마대전 장에서 손이 멈춘다. 그 장만 종이 색이 미세하게 다르다. 제본 실을 살펴보면 — 그 몇 장만 나중에 다시 꿰맨 흔적이 있다. 장의 끝, 작은 붉은 도장: 「왕립 기록원 — 교정필」. 오웬이 도장의 날짜를 확인한다. 삼백 년 전. 그는 안경을 벗고, 오래 눈을 감는다. 의심은 '오래전 누군가'를 향한다. 미르엘은 등장하지 않는다.","refs":["미르엘 삼면도.jpg","스토리 NPC 일러스트.png"]},
  {"id":"ep16-a","scene":"EP16 [CUTSCENE 16-A] 지워진 한 글자","full":false,"shot":"오웬이 빛 수정구로 오래된 문서의 지워진 줄을 비춘다. 긁어낸 자국 사이로, 단 한 글자만 살아남아 있다. 「왕」. 그 옆 여백에도 같은 붉은 도장이 찍혀 있다. 「왕립 기록원 — 교정필」.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep17-a","scene":"EP17 [CUTSCENE 17-A] 천공의 빛","full":false,"shot":"밤하늘. 기숙사 옥상에서 일행이 하늘을 올려다본다. 구름이 갈라지며 아주 먼 곳에 거대한 신전의 실루엣이 잠깐 나타났다 사라진다.","refs":[]},
  {"id":"ep18-a","scene":"EP18 [CUTSCENE 18-A] 축제","full":false,"shot":"교정에 작은 여름 축제. 등불, 노점, 하늘로 올라가는 마법 불꽃. 루스벨과 리안이 불꽃 쏘아 올리기 대결을 한다. 둘 다 점점 크게 쏘다가, 마지막 불꽃이 공중에서 부딪쳐 하트 모양이 된다. 주변 학생들이 환호한다. 둘은 동시에 얼굴이 시뻘게진다. 웃음소리 너머, 솜사탕 노점 앞. 미르엘이 솜사탕을 받아 들다가 학생들과 눈이 마주친다.","refs":["미르엘 삼면도.jpg","리안 삼면도.jpg"]},
  {"id":"ep19-a","scene":"EP19 [CUTSCENE 19-A] 자료 보관함","full":false,"shot":"수업이 끝난 뒤. 카엘이 섞여 들어간 3학년 자료를 보관함에 넣고 자물쇠를 채운다. 문서 맨 아래 귀퉁이에 「천공 신전 기록 사본 — 2학년 2학기 열람 예정」이라는 메모가 보인다.","refs":["카엘 삼면도.jpg"]},
  {"id":"ep20-a","scene":"EP20 [CUTSCENE 20-A] 분수의 네 갈래","full":false,"shot":"축제가 끝난 밤. 성녀가 혼자 중앙광장 분수대 앞에 선다. 분수 물줄기가 바람에 흩어지며 네 갈래로 갈라진다. 물보라 사이로, 아주 잠깐 오래된 문양이 떠오른다 — 네 개의 원. 그중 하나가 금빛으로 맺힌다. 분수 소리 사이로, 아주 멀리 땅 밑에서 무언가가 한 번 고동친다. 성녀가 발밑을 내려다본다. 아무것도 없다.","refs":[]},
  {"id":"ep21-a","scene":"EP21 [CUTSCENE 21-A] 성녀와 첫 대화","full":false,"shot":"빛으로 인장 사본을 비추자, '현재 역사'의 문양 아래로 다른 형태의 문양이 겹쳐 나타난다. 위의 문양은 사슬. 아래의 문양은 — 왕관을 두른 네 개의 원.","refs":[]},
  {"id":"ep22-a","scene":"EP22 [CUTSCENE 22-A] 중간고사: 빛과 기록","full":false,"shot":"도서관. 오웬이 오래된 문서를 빛으로 비춘다. '마왕이 먼저 칼을 들었다'라는 문구가 잠시 흐릿해지고, 그 아래로 다른 글자의 획이 비친다. 읽을 수는 없다. 다만 문장의 길이가 다르다. 아래 문장이 훨씬 길다.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep23-a","scene":"EP23 [CUTSCENE 23-A] 네 개의 빈자리","full":false,"shot":"일행이 떠나기 직전, 벽화의 네 상징 중 하나가 약하게 빛난다 — 금빛. 종소리가 울리고, 빛이 꺼진다. 신전 밖에서 첫 번째 폭풍 돌풍이 몰아친다.","refs":[]},
  {"id":"ep24-a","scene":"EP24 [CUTSCENE 24-A] 학교의 밤","full":false,"shot":"기숙사 창가. 주인공이 창밖 하늘을 바라본다. 멀리 구름 사이로 천공 신전이 작게 반짝인다. 동시에 — 아무도 없는 본관 지하, 철문의 문양이 금빛으로 희미하게 반응한다. 입학식 날 밤보다 조금 더 밝게.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep24-b","scene":"EP24 [INTERLUDE 24-B] 같은 시각, 화산지대 (막간)","full":true,"shot":"마물 마을의 광장. 아이 마족들이 뿔의 그림자를 둘러싸고 있다. 그녀가 무릎에 아이 하나를 앉혀 옛날이야기를 해 주고 있다. 아이들이 웃으며 흩어진다. 그녀가 혼자 남아 자기 가슴께에 손을 얹는다. 손바닥 아래에서, 아주 작은 금빛이 반딧불처럼 한 번 깜빡인다. 화면 암전.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png","스토리 NPC 일러스트.png"]},
  {"id":"ep25-a","scene":"EP25 [CUTSCENE 25-A] 대성당으로 가는 겨울길","full":false,"shot":"부조 속 왕의 손등에 새겨진 네 개의 원. 그중 하나가 촛불도 없는데 푸르게 빛난다. 눈물방울 모양으로.","refs":[]},
  {"id":"ep26-a","scene":"EP26 [CUTSCENE 26-A] 네 개로 나뉜 마음","full":false,"shot":"벽화의 왕관 부분. 원래 이름이 있었던 자리에 홈이 긁혀 있다. 그 아래 기록관 문장이 '확인 완료'의 표시처럼 찍혀 있다. 오웬이 그 문장을 손끝으로 쓸어 본다. 자기 도서관 열쇠고리에 달린 것과 같은 모양이다.","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep27-a","scene":"EP27 [CUTSCENE 27-A] 읽지 못한 문장","full":false,"shot":"울토르 도서관. 밤. 오웬이 가져온 탁본들을 벽 하나에 전부 붙인다. 해저 문, 천공 신전, 대성당 벽화. 같은 문자, 같은 네 개의 원. 그리고 그 옆에 한 줄의 메모: 「읽지 못하는 것은 우리만이 아니다. '읽지 못하게 만든' 사람이 있다.」","refs":["스토리 NPC 일러스트.png"]},
  {"id":"ep28-a","scene":"EP28 [CUTSCENE 28-A] 천공 아래서 찾은 길","full":false,"shot":"무너진 성문 너머로 버려진 신전의 실루엣. 안개가 신전을 휘감고 있다. 문 위의 네 원 문양 중 하나가 희미하게, 붉게 빛난다. 지금까지 본 것들과 달리 — 따뜻하지 않다.","refs":[]},
  {"id":"ep29-a","scene":"EP29 [CUTSCENE 29-A] 중간고사: 고대마법과 역사의 빈칸","full":false,"shot":"채점실. 미르엘이 마지막 문제의 답안지들을 넘긴다. 리안의 답안에서 손이 멈춘다. 여백에 동그라미 하나. 그리고 1학년 때와 같은 글씨로, 한 단어. 「좋다.」 리안의 성장을 보여 주는 장면. 미르엘은 좋은 교사로 보인다.","refs":["미르엘 삼면도.jpg","리안 삼면도.jpg"]},
  {"id":"ep30-a","scene":"EP30 [CUTSCENE 30-A] 버려진 폐허의 기록자","full":false,"shot":"기록자의 기억. 오래전 이 서고. 회색 망토를 입은 사람들이 특정 책장만 골라 불태운다. 불길 속에서 기록자가 장부 한 권을 품에 안고 쓰러진다. 그 장부가 지금, 잿더미 속에 남아 있다. 표지에는 울토르 기록관의 옛 문장 — 펜과 열쇠.","refs":[]},
  {"id":"ep31-a","scene":"EP31 [CUTSCENE 31-A] 신전으로 이어지는 균열","full":false,"shot":"일행이 떠난 뒤, 빈 방. 네 개의 자리 중 세 곳은 오래전에 비어 먼지만 쌓여 있다. 남은 한 자리만 검붉게 갈라져 있다. 갈라진 틈에서 아주 약한 열기가 숨처럼 새어 나온다.","refs":[]},
  {"id":"ep32-a","scene":"EP32 [CUTSCENE 32-A] 방학 원정, 마지막 평온","full":false,"shot":"모닥불 주위의 평범한 밤. 카메라가 천천히 멀어져 어둠 속 신전 입구를 비춘다. 돌 틈에서 아주 작은 균열이 생긴다. 균열 사이로 붉은빛이 한 번, 맥박친다. 모닥불 앞, 잠든 루스벨이 이마를 찡그린다. 꿈속에서 누군가에게 대답하듯 입술이 움직인다.","refs":[]},
  {"id":"ep33-a","scene":"EP33 [CUTSCENE 33-A] 죽은 자가 기억하는 전쟁","full":false,"shot":"환영이 바뀐다. 불타는 왕도. 뿔 달린 왕이 성문 앞에서 피난민들을 — 인간과 마족 모두를 — 먼저 성 밖으로 내보낸다. 왕은 마지막으로 성 안을 한 번 돌아보고, 홀로 남는다. 성문이 닫힌다. 아무도 대답하지 못한다. 환영이 사라진다.","refs":["모르스 1페이즈(망토, 면류관), 2페이즈(망토, 면류관 없음) 삼면도.png"]},
  {"id":"ep34-a","scene":"EP34 [CUTSCENE 34-A] 문을 열지 말 것","full":false,"shot":"석문이 아주 조금 열린다. 틈 사이로 뜨거운 바람이 새어 나온다. 그리고 누군가의 속삭임. 낮고, 갈라지고, 화가 난 목소리. 신전 내부의 검붉은 빛이 한 번 깜빡인다. 루스벨만 그 자리에 굳어 선다. 그녀의 귀에는 다른 말이 들렸다.","refs":[]},
]
